import type {
  VibeAgentActionDescriptor,
  VibeAgentToolName,
} from "./types";

export const vibeAgentActionRegistry: Record<VibeAgentToolName, VibeAgentActionDescriptor> = {
  inspect_project: {
    id: "inspect_project",
    label: "读取项目",
    description: "读取 Project.vibe、镜头、素材和队列摘要，只观察不修改。",
    mutatesProject: false,
    callsProvider: false,
    requiresConfirmation: false,
    minimumPermission: "plan_only",
  },
  classify_assets: {
    id: "classify_assets",
    label: "整理素材",
    description: "扫描项目素材，把图片、声音、视频、脚本和证据分成可确认的用途建议。",
    mutatesProject: false,
    callsProvider: false,
    requiresConfirmation: false,
    minimumPermission: "plan_only",
  },
  scan_assets: {
    id: "scan_assets",
    label: "检查素材缺口",
    description: "兼容旧时间线记录；新 Agent Turn 使用 classify_assets。",
    mutatesProject: false,
    callsProvider: false,
    requiresConfirmation: false,
    minimumPermission: "plan_only",
  },
  plan_story: {
    id: "plan_story",
    label: "拆故事",
    description: "把想法整理成故事段落、镜头和适合的导演 Skills。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: true,
    minimumPermission: "project_write_allowed",
  },
  plan_next_action: {
    id: "plan_next_action",
    label: "判断下一步",
    description: "结合用户意图、项目状态和权限边界，选择下一步待确认动作。",
    mutatesProject: false,
    callsProvider: false,
    requiresConfirmation: false,
    minimumPermission: "plan_only",
  },
  revise_shot: {
    id: "revise_shot",
    label: "改这一段",
    description: "根据当前点选的镜头、段落或素材，重写对应项目内容。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: true,
    minimumPermission: "project_write_allowed",
  },
  write_agent_message: {
    id: "write_agent_message",
    label: "写入回复",
    description: "把观察、判断、权限边界和下一步整理成创作者能看懂的 Agent 回复。",
    mutatesProject: false,
    callsProvider: false,
    requiresConfirmation: false,
    minimumPermission: "plan_only",
  },
  write_project: {
    id: "write_project",
    label: "修改项目",
    description: "把已确认的故事、镜头、策略或复核结果写回项目记录。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: true,
    minimumPermission: "project_write_allowed",
  },
  research_style: {
    id: "research_style",
    label: "查风格资料",
    description: "按用户指定风格检索或整理资料，生成可进入项目的导演参考。",
    mutatesProject: true,
    callsProvider: true,
    requiresConfirmation: true,
    minimumPermission: "project_write_allowed",
  },
  generate_references: {
    id: "generate_references",
    label: "生成参考",
    description: "调用现有参考图/故事板生成链路，为缺失镜头或素材补齐可复核参考。",
    mutatesProject: true,
    callsProvider: true,
    requiresConfirmation: true,
    minimumPermission: "reference_allowed",
  },
  compile_video_request: {
    id: "compile_video_request",
    label: "准备视频请求",
    description: "把镜头、参考、Skills 和 QA 结果编译成可复核的视频请求，不直接提交。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: true,
    minimumPermission: "project_write_allowed",
  },
  submit_video: {
    id: "submit_video",
    label: "提交视频",
    description: "将已复核片段按串行队列提交到 Seedance，并记录 submit id。",
    mutatesProject: true,
    callsProvider: true,
    requiresConfirmation: true,
    minimumPermission: "video_allowed",
  },
  query_video: {
    id: "query_video",
    label: "查询视频",
    description: "读取视频任务回流状态并同步预览，不重复提交任务。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: false,
    minimumPermission: "project_write_allowed",
  },
  export_project: {
    id: "export_project",
    label: "导出项目",
    description: "生成交付包、报告和最终文件路径。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: true,
    minimumPermission: "export_allowed",
  },
  export_showcase: {
    id: "export_showcase",
    label: "导出展示包",
    description: "导出软件截图、参考、prompt、submit id、视频段和展示说明。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: true,
    minimumPermission: "export_allowed",
  },
  save_skill: {
    id: "save_skill",
    label: "保存导演经验",
    description: "把当前成功做法沉淀成项目 Skill 草稿，确认后写入 skill-index。",
    mutatesProject: true,
    callsProvider: false,
    requiresConfirmation: true,
    minimumPermission: "project_write_allowed",
  },
  request_user_confirmation: {
    id: "request_user_confirmation",
    label: "请求确认",
    description: "对会写项目、生成参考、提交视频或导出的动作生成明确确认请求。",
    mutatesProject: false,
    callsProvider: false,
    requiresConfirmation: false,
    minimumPermission: "plan_only",
  },
  run_confirmed_action: {
    id: "run_confirmed_action",
    label: "执行已确认动作",
    description: "只执行已经通过权限门和用户确认的白名单动作。",
    mutatesProject: true,
    callsProvider: true,
    requiresConfirmation: true,
    minimumPermission: "project_write_allowed",
  },
};

export function listVibeAgentActionNames(): VibeAgentToolName[] {
  return Object.keys(vibeAgentActionRegistry)
    .filter((name) => name !== "scan_assets")
    .sort() as VibeAgentToolName[];
}

export function getVibeAgentActionDescriptor(name: VibeAgentToolName): VibeAgentActionDescriptor {
  return vibeAgentActionRegistry[name];
}
