import fs from "node:fs";

function readText(path: string) {
  return fs.readFileSync(path, "utf8");
}

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(message);
}

function stripComments(source: string) {
  return source
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/(^|[^:])\/\/.*$/gm, "$1");
}

function findFunctionBody(source: string, functionName: string) {
  const signature = `function ${functionName}`;
  const start = source.indexOf(signature);
  assert(start >= 0, `${functionName} is missing`);

  const paramsOpen = source.indexOf("(", start);
  assert(paramsOpen >= 0, `${functionName} has no parameter list`);

  let paramDepth = 0;
  let paramsClose = -1;
  for (let index = paramsOpen; index < source.length; index += 1) {
    const char = source[index];
    if (char === "(") paramDepth += 1;
    if (char === ")") paramDepth -= 1;
    if (paramDepth === 0) {
      paramsClose = index;
      break;
    }
  }
  assert(paramsClose >= 0, `${functionName} parameter list was not closed`);

  const open = source.indexOf("{", paramsClose);
  assert(open >= 0, `${functionName} has no function body`);

  let depth = 0;
  for (let index = open; index < source.length; index += 1) {
    const char = source[index];
    if (char === "{") depth += 1;
    if (char === "}") depth -= 1;
    if (depth === 0) return source.slice(open + 1, index);
  }

  throw new Error(`${functionName} body was not closed`);
}

const minimalAgentPanelSource = stripComments(readText("src/ui/director/MinimalAgentPanel.tsx"));
const agentPanelProjectionSource = stripComments(readText("src/ui/director/agentPanelProjection.ts"));
const appSource = stripComments(readText("src/App.tsx"));
const directorAgentPermissionIntentSource = stripComments(readText("src/core/directorAgentPermissionIntent.ts"));
const directorAgentActionSource = stripComments(readText("src/core/directorAgentAction.ts"));
const directorModeSource = stripComments(readText("src/ui/director/DirectorModeShell.tsx"));
const image2AssetActionSource = stripComments(readText("src/ui/director/useImage2AssetGenerationAction.ts"));
const seedanceVideoSubmitActionSource = stripComments(readText("src/ui/director/useSeedanceVideoSubmitAction.ts"));
const stylesSource = stripComments(readText("src/styles/director.css"));

const suggestedIntentFromStatusInspection = findFunctionBody(minimalAgentPanelSource, "suggestedIntentFromStatusInspection");
const agentActionPathStepLabel = findFunctionBody(minimalAgentPanelSource, "agentActionPathStepLabel");
const agentActionPathItems = findFunctionBody(minimalAgentPanelSource, "agentActionPathItems");
const agentReviewPrimaryLabel = findFunctionBody(minimalAgentPanelSource, "agentReviewPrimaryLabel");
const prepareChange = findFunctionBody(minimalAgentPanelSource, "prepareChange");
const handleNext = findFunctionBody(minimalAgentPanelSource, "handleNext");
const buildConfirmedAgentToolHandoff = findFunctionBody(minimalAgentPanelSource, "buildConfirmedAgentToolHandoff");
const runConfirmedAgentTool = findFunctionBody(minimalAgentPanelSource, "runConfirmedAgentTool");
const agentToolRecordLabel = findFunctionBody(minimalAgentPanelSource, "agentToolRecordLabel");
const agentToolOnlyNeedsConfirmation = findFunctionBody(minimalAgentPanelSource, "agentToolOnlyNeedsConfirmation");
const agentToolPlannedResultLabel = findFunctionBody(minimalAgentPanelSource, "agentToolPlannedResultLabel");
const agentToolResultLabel = findFunctionBody(minimalAgentPanelSource, "agentToolResultLabel");
const agentShotScopeLabel = findFunctionBody(minimalAgentPanelSource, "agentShotScopeLabel");
const agentTargetScopeLabel = findFunctionBody(minimalAgentPanelSource, "agentTargetScopeLabel");
const agentToolScopeLabel = findFunctionBody(minimalAgentPanelSource, "agentToolScopeLabel");
const agentToolReceiptLabel = findFunctionBody(minimalAgentPanelSource, "agentToolReceiptLabel");
const agentToolFollowUpLabel = findFunctionBody(minimalAgentPanelSource, "agentToolFollowUpLabel");
const agentResultViewTarget = findFunctionBody(minimalAgentPanelSource, "agentResultViewTarget");
const openAgentResultView = findFunctionBody(minimalAgentPanelSource, "openAgentResultView");
const agentActionConfirmationFacts = findFunctionBody(minimalAgentPanelSource, "agentActionConfirmationFacts");
const agentExecutionTraceItems = findFunctionBody(minimalAgentPanelSource, "agentExecutionTraceItems");
const agentCapabilityItems = findFunctionBody(minimalAgentPanelSource, "agentCapabilityItems");
const agentCapabilityGlanceItems = findFunctionBody(minimalAgentPanelSource, "agentCapabilityGlanceItems");
const composerAttachmentUseHint = findFunctionBody(minimalAgentPanelSource, "composerAttachmentUseHint");
const attachmentIntentLine = findFunctionBody(minimalAgentPanelSource, "attachmentIntentLine");
const composerIntentFromInput = findFunctionBody(minimalAgentPanelSource, "composerIntentFromInput");
const agentActionScopeLabel = findFunctionBody(minimalAgentPanelSource, "agentActionScopeLabel");
const agentConfirmedProjectWriteLabel = findFunctionBody(minimalAgentPanelSource, "agentConfirmedProjectWriteLabel");
const agentNextControlledStepLabel = findFunctionBody(minimalAgentPanelSource, "agentNextControlledStepLabel");
const agentToolPreflightLabel = findFunctionBody(minimalAgentPanelSource, "agentToolPreflightLabel");
const agentToolHasPreflightBlocker = findFunctionBody(minimalAgentPanelSource, "agentToolHasPreflightBlocker");
const agentToolHandoffBindingIssue = findFunctionBody(minimalAgentPanelSource, "agentToolHandoffBindingIssue");
const agentExpectedReceiptLabel = findFunctionBody(minimalAgentPanelSource, "agentExpectedReceiptLabel");
const agentActionDiffs = findFunctionBody(minimalAgentPanelSource, "agentActionDiffs");
const creatorProjectTaskLabel = findFunctionBody(minimalAgentPanelSource, "creatorProjectTaskLabel");
const agentStatusInspectionFacts = findFunctionBody(minimalAgentPanelSource, "agentStatusInspectionFacts");
const confirmedAgentResultFacts = findFunctionBody(minimalAgentPanelSource, "confirmedAgentResultFacts");
const agentConfirmedResultNextStep = findFunctionBody(minimalAgentPanelSource, "agentConfirmedResultNextStep");
const confirmedToolRunResult = findFunctionBody(minimalAgentPanelSource, "confirmedToolRunResult");
const agentProjectRecordResultFacts = findFunctionBody(minimalAgentPanelSource, "agentProjectRecordResultFacts");
const referenceGenerationToolOutcome = findFunctionBody(minimalAgentPanelSource, "referenceGenerationToolOutcome");
const videoSubmitToolOutcome = findFunctionBody(minimalAgentPanelSource, "videoSubmitToolOutcome");
const currentAgentToolAvailability = findFunctionBody(minimalAgentPanelSource, "currentAgentToolAvailability");
const retryConfirmedAgentTool = findFunctionBody(minimalAgentPanelSource, "retryConfirmedAgentTool");
const confirmPlan = findFunctionBody(minimalAgentPanelSource, "confirmPlan");
const inspectNextAfterConfirmedAction = findFunctionBody(minimalAgentPanelSource, "inspectNextAfterConfirmedAction");
const continueNextAfterConfirmedAction = findFunctionBody(minimalAgentPanelSource, "continueNextAfterConfirmedAction");
const continueFromAgentActionLog = findFunctionBody(minimalAgentPanelSource, "continueFromAgentActionLog");
const openAgentActionLogResultView = findFunctionBody(minimalAgentPanelSource, "openAgentActionLogResultView");
const continueFromStatusActionPath = findFunctionBody(minimalAgentPanelSource, "continueFromStatusActionPath");
const updateVideoPermissionContract = findFunctionBody(minimalAgentPanelSource, "updateVideoPermissionContract");
const selectVideoPermissionMode = findFunctionBody(minimalAgentPanelSource, "selectVideoPermissionMode");
const detectVideoContract = findFunctionBody(agentPanelProjectionSource, "detectAgentVideoSubmitContract");
const labelVideoContract = findFunctionBody(agentPanelProjectionSource, "agentVideoSubmitContractLabel");
const detailVideoContract = findFunctionBody(agentPanelProjectionSource, "agentVideoSubmitContractDetail");
const selectionContextChips = findFunctionBody(minimalAgentPanelSource, "selectionContextChips");
const directorMode = findFunctionBody(directorModeSource, "DirectorMode");
const scopedAssetGenerationTarget = findFunctionBody(image2AssetActionSource, "scopedAssetGenerationTarget");
const scopedVideoShotIds = findFunctionBody(seedanceVideoSubmitActionSource, "scopedVideoShotIds");
const intentWithQaRevisionHint = findFunctionBody(minimalAgentPanelSource, "intentWithQaRevisionHint");
const revisePlan = findFunctionBody(minimalAgentPanelSource, "revisePlan");
const agentActionFieldLabel = findFunctionBody(minimalAgentPanelSource, "agentActionFieldLabel");
const preparedSelectionContextChips = findFunctionBody(minimalAgentPanelSource, "preparedSelectionContextChips");

assert(/setText\(""\)/.test(prepareChange), "MinimalAgentPanel must clear text after sending");
assert(/setAttachments\(\[\]\)/.test(prepareChange), "MinimalAgentPanel must clear attachments after sending");
assert(/localProjectReady = true/.test(minimalAgentPanelSource), "Agent composer must receive an explicit local-project readiness flag");
assert(/localProjectReady=\{folderReady\}/.test(directorMode), "Director mode must pass real folder readiness into the Agent composer");
assert(/const localProjectReadyForTools = Boolean\(localProjectReady\)/.test(minimalAgentPanelSource), "Agent tool readiness must distinguish browser drafts from local project folders");
assert(/const hasActiveSelection = hasBoundSelection \|\| hasSectionSelection/.test(minimalAgentPanelSource), "section selection must count as an active Agent context");
assert(/const liveSelectionChips = selectionContextChips/.test(minimalAgentPanelSource), "Agent composer must project the current selection into visible context chips");
assert(/const preparedSelectionChips = preparedSelectionContextChips/.test(minimalAgentPanelSource), "Agent composer must keep reviewed plans bound to their prepared selection chips");
assert(/workflow && preparedSelectionChips\.length \? preparedSelectionChips : liveSelectionChips/.test(minimalAgentPanelSource), "reviewed Agent plans must not show chips from a later live selection");
assert(/function compactAgentScopeLabel/.test(minimalAgentPanelSource), "bottom Agent header needs a compact creator-facing scope label");
assert(/const displayedCompactScopeLabel = compactAgentScopeLabel\(displayedScopeLabel\)/.test(minimalAgentPanelSource), "bottom Agent header must not render raw project or shot ids");
assert(/const displayedCompactSelectionHint = compactAgentSelectionHint\(displayedSelectionHint\)/.test(minimalAgentPanelSource), "bottom Agent selection hint must be cleaned before display");
assert(/<strong>\{displayedCompactScopeLabel\}<\/strong>/.test(minimalAgentPanelSource), "bottom Agent header must use the compact scope label");
assert(/hasActiveSelection \? "当前选择" : "怎么用"/.test(minimalAgentPanelSource), "selection header must reflect shot, asset, and section context");
assert(/hasActiveSelection[\s\S]*\? "说这块怎么改/.test(minimalAgentPanelSource), "composer placeholder must recognize selected sections as editable context");
assert(/aria-label="当前引用内容"/.test(minimalAgentPanelSource), "Agent composer must expose selected context chips accessibly");
assert(/input\.shot\.referenceStrategy/.test(selectionContextChips), "shot context chips must show the selected generation mode");
assert(/input\.asset\.type/.test(selectionContextChips), "asset context chips must show the selected asset type");
assert(/input\.sectionLabel/.test(selectionContextChips), "section context chips must show selected section context");
assert(/runtimeState\.storyFlow\.shots/.test(preparedSelectionContextChips), "prepared Agent chips must resolve shot ids against current Project.vibe state");
assert(/runtimeState\.visualMemory\.assets/.test(preparedSelectionContextChips), "prepared Agent chips must resolve asset ids against current visual memory");
assert(/\.minimal-agent-context-chips/.test(stylesSource), "selected context chips need dedicated styling");
assert(/MAX_COMPOSER_SCRIPT_CHARS/.test(minimalAgentPanelSource), "script attachments must have a bounded text read");
assert(/attachment\.kind !== "script"/.test(attachmentIntentLine), "non-script attachments must stay as asset references instead of prompt text");
assert(/composerAttachmentUseHint\(attachment\.kind\)/.test(attachmentIntentLine), "non-script attachments must carry a creator-facing use hint into the Agent intent");
assert(/角色、场景、道具或镜头参考/.test(composerAttachmentUseHint), "image attachments must be described as reference material to classify");
assert(/声音参考[\s\S]*角色、旁白或对白/.test(composerAttachmentUseHint), "audio attachments must be described as voice reference material");
assert(/节奏、构图或风格信息/.test(composerAttachmentUseHint), "video attachments must be described as video reference material");
assert(/await attachment\.file\.text\(\)/.test(attachmentIntentLine), "script attachments must read their file body into the staged Agent intent");
assert(/读取失败，请直接粘贴脚本正文/.test(attachmentIntentLine), "script attachment read failures must be creator-facing");
assert(/Promise\.all\(attachments\.map\(attachmentIntentLine\)\)/.test(composerIntentFromInput), "composer intent must resolve async attachment text before staging");
assert(/await composerIntentFromInput\(text,\s*attachments\)/.test(prepareChange), "send must wait for script attachment contents before staging");
assert(/正在读取脚本/.test(prepareChange), "send must show a readable status while importing script attachments");
assert(/aria-label="添加脚本、图片或声音参考"/.test(minimalAgentPanelSource), "Agent composer file button must expose a clear accessible label");
assert(/const primaryAriaLabel = primaryDisabled[\s\S]*primaryDisabledReason[\s\S]*const footerPrimaryAriaLabel[\s\S]*aria-label=\{footerPrimaryAriaLabel\}/.test(minimalAgentPanelSource), "Agent composer primary button must expose the action or blocker as an accessible label");
assert(/preparedContext\?\.userIntent\?\.trim\(\) \|\| await composerIntentFromInput\(text,\s*attachments\)/.test(minimalAgentPanelSource), "confirmation fallback must preserve imported script contents");
assert(/catch\s*\(error\)\s*\{[\s\S]*Failed to stage Product Agent plan[\s\S]*resetPreparedComposerState\("整理失败，请重试"\)[\s\S]*return;/.test(prepareChange), "Product Agent staging failures must stop instead of falling back to an unbacked local plan");
assert(/按发送前检查修改/.test(intentWithQaRevisionHint), "QA revision hints must use creator-facing wording");
assert(/feedback\.primaryAction/.test(intentWithQaRevisionHint), "QA revision hints must include the primary action");
assert(/intentWithQaRevisionHint\(preparedContext\?\.userIntent,\s*preparedContext\?\.qaFeedback\)/.test(revisePlan), "revising a blocked staged action should bring QA guidance back into the composer");
assert(/detectAgentVideoPermissionContract\(userIntent,\s*activeVideoPermissionContract\)/.test(prepareChange), "send must detect the video submit contract from creator input");
assert(/updateVideoPermissionContract\(nextVideoPermissionContract\)/.test(prepareChange), "send must write the session video submit contract");
assert(/const nextActionVideoPermissionContract = visibleVideoPermissionContractFor\(nextVideoPermissionContract\)/.test(prepareChange), "staged Agent actions must use the visible execution boundary for the current project state");
assert(/agentVideoPermissionForMode\(mode\)/.test(selectVideoPermissionMode), "creator should be able to switch the Agent execution boundary directly");
assert(/setLocalVideoPermissionContract\(nextContract\)/.test(updateVideoPermissionContract), "Agent execution boundary controls must update immediately in the composer");
assert(/const activeVideoPermissionContract = localVideoPermissionContract/.test(minimalAgentPanelSource), "Agent composer must not wait for parent state echo before showing the selected boundary");
assert(/const previousRuntimeProjectKeyRef = useRef\(""\)/.test(minimalAgentPanelSource), "Agent composer must remember the current project identity");
assert(/const runtimeProjectKey = \[[\s\S]*runtimeState\.project\.root[\s\S]*runtimeState\.sourceIndexSummary\.projectId/.test(minimalAgentPanelSource), "Agent composer must derive project identity from the current project root and Project.vibe id");
assert(/previousRuntimeProjectKeyRef\.current === runtimeProjectKey/.test(minimalAgentPanelSource), "Agent composer must detect actual project switches before clearing staged plans");
assert(/const hasComposerDraft = Boolean\(text\.trim\(\) \|\| attachments\.length\)/.test(minimalAgentPanelSource), "Agent composer must treat unsent text and attachments as project-bound draft state");
assert(/const hasProjectBoundAgentState = Boolean\(hasPreparedAgentState \|\| hasComposerDraft \|\| agentActionLog\.length\)/.test(minimalAgentPanelSource), "Agent composer project-switch reset must include drafts, staged plans, and recent actions");
assert(/if\s*\(!localProjectReadyForTools\)\s*\{[\s\S]*restoredAgentLogKeyRef\.current = ""[\s\S]*setAgentActionLog\(\[\]\)[\s\S]*return;[\s\S]*const restoredItems = \(restoredAgentActionLog \|\| \[\]\)/.test(minimalAgentPanelSource), "browser drafts must not show restored local-project Agent action logs");
assert(/if\s*\(!localProjectReadyForTools\)\s*\{[\s\S]*restoredAgentDraftIdRef\.current = ""[\s\S]*return;[\s\S]*const draft = restoredAgentStagedPlanDraft/.test(minimalAgentPanelSource), "browser drafts must not auto-restore local-project staged Agent plans");
assert(/setText\(""\)[\s\S]*setAttachments\(\[\]\)[\s\S]*fileInputRef\.current\.value = ""[\s\S]*setWorkflow\(undefined\)/.test(minimalAgentPanelSource), "switching projects must clear stale composer text and files before clearing staged Agent state");
assert(/setAgentActionEnvelope\(undefined\)[\s\S]*setAgentToolHandoff\(undefined\)[\s\S]*restoredAgentDraftIdRef\.current = ""[\s\S]*项目已切换，重新发送即可/.test(minimalAgentPanelSource), "Agent composer must clear stale staged actions and restored draft markers when the project changes");
assert(/if\s*\(\s*workflow\s*\)\s*return/.test(selectVideoPermissionMode), "execution boundary controls must not rewrite an already staged plan");
assert(/aria-pressed=\{videoPermissionContractForUi\.mode === item\.mode\}/.test(minimalAgentPanelSource), "execution boundary controls must be accessible segmented buttons");
assert(/onClick=\{\(\) => selectVideoPermissionMode\(item\.mode\)\}/.test(minimalAgentPanelSource), "execution boundary buttons must update the session contract");
assert(/agentVideoSubmitContractForMode/.test(agentPanelProjectionSource), "Agent execution boundary must have a reusable contract builder");
assert(/agentVideoSubmitContractAllowsReference as agentVideoPermissionAllowsReference/.test(minimalAgentPanelSource), "reference generation controls must use the shared session contract");
assert(/const referenceGenerationBlockedByContract = !agentVideoPermissionAllowsReference\(currentVideoPermissionContract\)/.test(minimalAgentPanelSource), "reference generation controls must derive their lock from the currently visible boundary");
assert(/videoPermissionContract:\s*nextActionVideoPermissionContract/.test(prepareChange), "prepared context must carry the visible video submit contract");
assert(/buildDirectorAgentActionEnvelope\(\{/.test(prepareChange), "send must create a staged product-agent action envelope");
assert(/await onStagePrototypeAgentPlan\?\.\(\{/.test(prepareChange), "send must ask the App/Product Agent loop for the staged action");
assert(/availability:\s*currentAgentToolAvailability\(\)/.test(prepareChange), "staged Product-Agent handoff must receive live tool availability");
assert(/choosePreparedAgentAction\(\s*localAgentActionEnvelope,\s*stagedAgentPlan\?\.agentActionEnvelope,\s*\)/.test(prepareChange), "send must reconcile Product-Agent staged actions with locally recognized tool commands");
assert(/setAgentActionEnvelope\(nextAgentActionEnvelope\)/.test(prepareChange), "send must store the staged product-agent action envelope");
assert(/setAgentToolHandoff\(stagedAgentPlan\?\.agentToolHandoff\)/.test(prepareChange), "send must keep the staged Agent tool handoff for review");
assert(/projectRecordLabel:\s*stagedAgentPlan\?\.projectRecordLabel/.test(prepareChange), "send must keep the staged Project.vibe record summary for review");
assert(/projectImpactLabel:\s*stagedAgentPlan\?\.projectImpactLabel/.test(prepareChange), "send must keep the staged Project.vibe impact summary for review");
assert(/projectTaskLabel:\s*stagedAgentPlan\?\.projectTaskLabel/.test(prepareChange), "send must keep the staged Project.vibe task summary for review");
assert(/void prepareChange\(\)/.test(minimalAgentPanelSource), "send handler must await the async staged Agent path without blocking React events");
assert(/agentActionTargetShotIds\(nextAgentActionEnvelope\)/.test(prepareChange), "send must reuse Agent-resolved shot targets when the creator names a shot");
assert(/finalPreparedSelection[\s\S]*selectedShotId:[\s\S]*agentResolvedShotIds\.length === 1/.test(prepareChange), "prepared context must carry single Agent-resolved shot targets");
assert(/finalPreparedSelection[\s\S]*selectedShotIds:[\s\S]*agentResolvedShotIds\.length > 1/.test(prepareChange), "prepared context must carry multi-shot Agent-resolved targets");
assert(/directorAgentExecutionContractFromCreatorBoundary/.test(prepareChange), "agent action envelope must receive the creator-facing execution contract");
assert(/mode:\s*nextActionVideoPermissionContract\.mode[\s\S]*referenceGenerationAllowed:\s*nextActionVideoPermissionContract\.referenceGenerationAllowed[\s\S]*videoSubmitAllowed:\s*nextActionVideoPermissionContract\.videoSubmitAllowed/.test(prepareChange), "agent action envelope must use the visible execution boundary");
assert(/feedbackWithSubmitCheckContext\(userIntent,\s*videoSendAction\?\.qaFeedback\)/.test(prepareChange), "director feedback must inherit the latest submit-check context");
assert(/confirmedAgentResult/.test(minimalAgentPanelSource), "confirmed Agent result should be retained in the bottom composer");
assert(/const prototypeAgentDemo = planPhase === "confirmed" && localPrototypeAgentDemo[\s\S]*\? localPrototypeAgentDemo[\s\S]*: latestPrototypeAgentDemo \|\| localPrototypeAgentDemo/.test(minimalAgentPanelSource), "confirmed tool results must take precedence over parent-level preparation status");
assert(/showAgentResultNote/.test(minimalAgentPanelSource), "bottom composer should render a compact confirmed-result note");
assert(/aria-label="上次动作结果"/.test(minimalAgentPanelSource), "confirmed-result note should be accessible and creator-facing");
assert(/const \[agentActionLog,\s*setAgentActionLog\]/.test(minimalAgentPanelSource), "Agent composer must keep a small current-project action log");
assert(/function agentActionLogItemFromResult/.test(minimalAgentPanelSource), "confirmed Agent actions must be converted into creator-facing log items");
assert(/followUpIntent/.test(minimalAgentPanelSource), "Agent action log items must carry a follow-up prompt for the next staged action");
assert(/createdAt:\s*new Date\(\)\.toISOString\(\)/.test(minimalAgentPanelSource), "Agent action log items must carry a persisted timestamp");
assert(/继续刚才的动作/.test(minimalAgentPanelSource), "Agent action log follow-up prompt must be creator-facing");
assert(/function rememberAgentActionLogItem/.test(minimalAgentPanelSource), "Agent action log must dedupe by action id and stay bounded");
assert(/function rememberConfirmedAgentActionLogItem/.test(minimalAgentPanelSource), "remembering a confirmed action must go through the persistence-aware helper");
assert(/onRememberAgentActionLogItem\?\.\(item\)/.test(minimalAgentPanelSource), "confirmed Agent actions must be offered to the project-level action log sidecar");
assert(/restoredAgentActionLog\?: ProjectAgentActionLogItem\[\]/.test(minimalAgentPanelSource), "Agent composer must accept restored project-level action log items");
assert(/rememberAgentActionLogItem[\s\S]*slice\(0,\s*4\)/.test(minimalAgentPanelSource), "Agent action log must keep only a compact recent window");
assert(/setAgentActionLog\(\[\]\)[\s\S]*项目已切换，重新发送即可/.test(minimalAgentPanelSource), "Agent action log must clear when the current project changes");
assert(/failedFeedbackRun[\s\S]*rememberConfirmedAgentActionLogItem\([\s\S]*agentActionLogItemFromResult\(agentActionEnvelope,\s*agentToolHandoff,\s*failedFeedbackRun/.test(confirmPlan), "failed feedback saves must still leave a recent Agent action record");
assert(/failedRun[\s\S]*动作执行失败，项目已保留[\s\S]*rememberConfirmedAgentActionLogItem\([\s\S]*agentActionLogItemFromResult\(agentActionEnvelope,\s*confirmedAgentToolHandoff \|\| agentToolHandoff,\s*failedRun/.test(confirmPlan), "failed confirmed tool runs must still leave a recent Agent action record");
assert(/failedRetryRun[\s\S]*rememberConfirmedAgentActionLogItem\([\s\S]*agentActionLogItemFromResult\(agentActionEnvelope,\s*refreshedHandoff,\s*failedRetryRun/.test(retryConfirmedAgentTool), "failed retries must still leave a recent Agent action record");
assert(/aria-label="最近动作"/.test(minimalAgentPanelSource), "Agent composer must show recent confirmed actions in user-facing language");
assert(/resetPreparedComposerState\("继续写"\)/.test(continueFromAgentActionLog), "clicking a recent Agent action must return to editable composer state");
assert(/setText\(item\.followUpIntent\)/.test(continueFromAgentActionLog), "clicking a recent Agent action must prefill follow-up context");
assert(!/confirmPlan\(|runConfirmedAgentTool\(|prepareChange\(/.test(continueFromAgentActionLog), "clicking a recent Agent action must not execute or stage automatically");
assert(/onClick=\{\(\) => continueFromAgentActionLog\(item\)\}/.test(minimalAgentPanelSource), "recent Agent actions must be clickable follow-up entries");
assert(/type AgentActionLogItem = ProjectAgentActionLogItem/.test(minimalAgentPanelSource), "recent Agent action records must use the project-level persisted item shape");
assert(/const resultView = blocked \? undefined : agentResultViewTarget\(handoff\)/.test(minimalAgentPanelSource), "failed or blocked recent Agent action records must not expose result navigation");
assert(/if \(!item\.resultView\) return/.test(openAgentActionLogResultView), "recent Agent action result navigation must no-op without a target");
assert(/onOpenResultView\?\.?\(item\.resultView\.view\)/.test(openAgentActionLogResultView), "recent Agent action result navigation should only switch the visible director view");
assert(!/confirmPlan\(|runConfirmedAgentTool\(|prepareChange\(|onCreateP6RealSample|onSendSeedanceVideo|onRunExport/.test(openAgentActionLogResultView), "recent Agent action result navigation must not execute, stage, or submit tools");
assert(/onClick=\{\(\) => openAgentActionLogResultView\(item\)\}[\s\S]*item\.resultView\.label/.test(minimalAgentPanelSource), "recent Agent actions must expose a direct result-view button when possible");
assert(/confirmedAgentResultFacts/.test(minimalAgentPanelSource), "confirmed Agent result should expose project/tool status facts");
assert(/result\.projectRestored[\s\S]*已恢复项目[\s\S]*result\.projectSaved/.test(confirmedAgentResultFacts), "confirmed result facts must distinguish restored drafts from new project writes");
assert(/projectSaved/.test(confirmedAgentResultFacts), "confirmed result facts must distinguish saved project writes");
assert(/projectVibeAdded/.test(confirmedAgentResultFacts), "confirmed result facts must distinguish Project.vibe writeback");
assert(/label:\s*"结果"/.test(confirmedAgentResultFacts), "confirmed result facts must start with a creator-facing result summary");
assert(/label:\s*"影响"[\s\S]*projectImpactLabel/.test(confirmedAgentResultFacts), "confirmed result facts must expose affected project scope");
assert(/label:\s*"待处理"[\s\S]*projectTaskLabel/.test(confirmedAgentResultFacts), "confirmed result facts must expose queued follow-up work");
assert(/const resultHasError = run\?\.status === "error" \|\| result\?\.status === "error"/.test(confirmedAgentResultFacts), "confirmed result facts must detect failed or blocked tool outcomes");
assert(/resultHasError[\s\S]*handoff \? agentConfirmedResultNextStep\(handoff,\s*run\) : "调整后可重试"/.test(confirmedAgentResultFacts), "failed or blocked outcomes must show retry-oriented next steps instead of review copy");
assert(/label:\s*"下一步"[\s\S]*agentConfirmedResultNextStep/.test(confirmedAgentResultFacts), "confirmed result facts must tell the creator where to review the actual tool result next");
assert(/return facts\.slice\(0,\s*4\)/.test(confirmedAgentResultFacts), "confirmed result facts must stay compact");
assert(!/有内容待补/.test(appSource), "Project.vibe task summaries should avoid awkward placeholder copy");
assert(/有内容待补后入队[\s\S]*生成参考后继续/.test(creatorProjectTaskLabel), "restored Agent plans should sanitize old awkward queued-task copy");
assert(/有内容待补[\s\S]*先生成参考/.test(creatorProjectTaskLabel), "restored Agent plans should sanitize old missing-reference copy");
assert(/不用再执行[\s\S]*只写项目/.test(creatorProjectTaskLabel), "restored Agent plans should sanitize old no-op copy");
assert(/status === "error"[\s\S]*调整后可重试/.test(agentConfirmedResultNextStep), "failed confirmed tool results should point to retry instead of a review lane");
assert(/previewReady[\s\S]*去预览确认/.test(agentConfirmedResultNextStep), "preview-ready confirmed tool results should point to preview review");
assert(/image2_reference_generation[\s\S]*去参考区看进度[\s\S]*去参考区复核/.test(agentConfirmedResultNextStep), "reference generation result next step should distinguish running from review-ready");
assert(/seedance_video_submit[\s\S]*等视频结果[\s\S]*去预览确认/.test(agentConfirmedResultNextStep), "video submit result next step should distinguish queueing from returned preview");
assert(/project_export[\s\S]*等导出完成[\s\S]*去交付页查看/.test(agentConfirmedResultNextStep), "export result next step should distinguish running from delivered output");
assert(/handler === "web_search" \|\| handoff\.handler === "image2_reference_generation"\) return \{ view: "assets", label: "去参考" \}/.test(agentResultViewTarget), "web research and reference generation results should route creators to references");
assert(/seedance_video_submit[\s\S]*view: "preview"[\s\S]*label: "去预览"/.test(agentResultViewTarget), "video submit results should route creators to preview");
assert(/project_export[\s\S]*view: "export"[\s\S]*label: "去导出"/.test(agentResultViewTarget), "export results should route creators to export");
assert(/project_vibe_patch[\s\S]*view: "story"[\s\S]*label: "回故事"/.test(agentResultViewTarget), "project patch results should route creators back to story");
assert(/onOpenResultView\?\.?\(target\.view\)/.test(openAgentResultView), "result navigation should only switch the visible director view");
assert(!/confirmPlan\(|runConfirmedAgentTool\(|prepareChange\(|onCreateP6RealSample|onSendSeedanceVideo|onRunExport/.test(openAgentResultView), "result navigation must not execute, stage, or submit tools");
assert(/projectRecordLabel:\s*previewResult\?\.projectRecordLabel/.test(agentProjectRecordResultFacts), "confirmed tool result should inherit the app-level project record summary");
assert(/projectImpactLabel:\s*previewResult\?\.projectImpactLabel/.test(agentProjectRecordResultFacts), "confirmed tool result should inherit affected project scope");
assert(/projectTaskLabel:\s*previewResult\?\.projectTaskLabel/.test(agentProjectRecordResultFacts), "confirmed tool result should inherit queued follow-up work");
assert(/confirmedToolRunResult\(authoritativeAgentToolHandoff,\s*toolRunOutcome,\s*previewResult(?:\s*\|\|\s*undefined)?\)/.test(minimalAgentPanelSource), "confirmed tool result must keep the Project.vibe receipt summary returned by the app");
assert(/agentActionEnvelope\?:\s*DirectorAgentActionEnvelope/.test(agentPanelProjectionSource), "App/Product-Agent preview result must be able to return the authoritative action envelope");
assert((appSource.match(/agentActionEnvelope:\s*productAgentLoop\.action/g) || []).length >= 3, "App must return the confirmed Product-Agent action envelope with every preview result path");
assert(/handoff\?\.status === "handled_by_project_write"[\s\S]*修改已写入项目[\s\S]*previewReady:\s*false/.test(confirmedToolRunResult), "project-only handoffs must show project-write status instead of generic preview-ready copy");
assert(/handoff\.status !== "ready"[\s\S]*previewReady:\s*true/.test(confirmedToolRunResult), "non-tool confirmations may still fall back to preview-ready status");
assert(/handoff\.handler === "web_search"[\s\S]*资料已整理，等你确认[\s\S]*previewReady:\s*false/.test(confirmedToolRunResult), "web-search tool results must not pretend a preview was generated");
assert(/handoff\.handler === "image2_reference_generation"[\s\S]*参考已开始生成[\s\S]*previewReady:\s*false/.test(confirmedToolRunResult), "reference-generation tool results must not pretend a preview was generated");
assert(/handoff\.handler === "seedance_video_submit"[\s\S]*视频已发送，排队后回到预览[\s\S]*previewReady:\s*false/.test(confirmedToolRunResult), "video-submit tool results must preserve queue semantics instead of preview-ready status");
assert(/handoff\.handler === "project_export"[\s\S]*toolRunOutcome\?\.label \|\| "导出已开始"[\s\S]*previewReady:\s*false/.test(confirmedToolRunResult), "export tool results must reflect the real export outcome and not pretend a preview was generated");
assert(/handoff\.handler === "project_export"[\s\S]*status:\s*toolRunOutcome\?\.resultStatus \|\| "running"/.test(confirmedToolRunResult), "export tool results must preserve the real ready/running status inside the visible result");
assert(/toolRunOutcome\?\.status === "failed" \|\| toolRunOutcome\?\.status === "blocked"[\s\S]*项目已保留/.test(confirmedToolRunResult), "failed or blocked tool runs must not be reported as successful tool results");
assert(/const label = toolRunOutcome\?\.status === "completed" \? toolRunOutcome\.label/.test(confirmedToolRunResult), "confirmed tool result must surface the actual returned tool label");
assert(/toolRunOutcome\?\.waitingReview/.test(confirmedToolRunResult), "confirmed tool result must carry the actual review state");
assert(/toolRunOutcome\?\.previewReady/.test(confirmedToolRunResult), "confirmed tool result must carry the actual preview state");
assert(/state\?\.status === "needs_review" \|\| state\?\.status === "verified"/.test(referenceGenerationToolOutcome), "reference generation outcome must treat returned assets as review-ready");
assert(/参考已生成，去参考区复核/.test(referenceGenerationToolOutcome), "reference generation outcome must give a review-lane next step");
assert(/state\?\.status === "blocked" \|\| state\?\.status === "missing"/.test(referenceGenerationToolOutcome), "reference generation outcome must preserve blocked/missing tool states");
assert(/state\?\.status === "submitted"/.test(videoSubmitToolOutcome), "video submit outcome must preserve submitted queue state");
assert(/state\.qaFeedback\?\.summary/.test(videoSubmitToolOutcome), "video submit outcome must surface QA feedback when blocked");
assert(/aria-label="确认后的项目状态"/.test(minimalAgentPanelSource), "confirmed-result note must show project status after confirmation");
assert(/aria-label="已确认改动"/.test(minimalAgentPanelSource), "confirmed-result note must keep the accepted staged diff visible");
assert(!/aria-label="本次执行路径"/.test(minimalAgentPanelSource), "confirmed-result note should not repeat internal execution path after confirmation");
assert(!/minimal-agent-execution-trace is-confirmed/.test(minimalAgentPanelSource), "confirmed-result note should not repeat the pre-confirmation execution trace");
assert(/当前发送前提示/.test(minimalAgentPanelSource), "Agent panel must keep submit-check context in follow-up feedback");
assert(/videoSendAction\.qaFeedback\.summary/.test(minimalAgentPanelSource), "Agent panel must surface creator-facing submit-check feedback");
assert(/planFacts\.map\(\(fact,\s*index\) =>[\s\S]*key=\{`\$\{fact\.label\}:\$\{fact\.value\}:\$\{index\}`\}/.test(minimalAgentPanelSource), "Agent plan facts must use unique keys even when labels repeat");
assert(/videoPermissionContract:\s*confirmedVideoPermissionContract/.test(minimalAgentPanelSource), "preview handoff must carry the video submit contract");
assert(/preparePrototypeAgentDemo[\s\S]*executionContract:\s*input\.videoPermissionContract[\s\S]*providerSubmitAllowed:\s*input\.videoPermissionContract\.referenceGenerationAllowed \|\| input\.videoPermissionContract\.videoSubmitAllowed/.test(appSource), "confirmed Product-Agent preview loop must preserve the visible execution boundary even when rebuilding the action");
assert(/agentActionEnvelope,/.test(minimalAgentPanelSource), "preview handoff must carry the staged Agent action envelope");
assert(/proposedChanges/.test(agentActionDiffs), "staged Agent action diffs must be built from proposed changes");
assert(/agentActionFieldLabel/.test(agentActionDiffs), "staged Agent action diffs must use creator-facing field labels");
assert(/field === "nextActions"[\s\S]*后续动作/.test(agentActionFieldLabel), "Agent status facts should show the action path as creator-facing next actions");
assert(/value:[\s\S]*change\.from[\s\S]*change\.to/.test(agentActionDiffs), "staged Agent diffs must surface the concrete proposed value, including creator wording for scoped edits");
assert(/reason:\s*change\.reason/.test(agentActionDiffs), "staged Agent diffs must surface why and where the change will be written");
assert(/function agentActionIsStatusInspection/.test(minimalAgentPanelSource), "Agent panel must detect read-only project status inspections");
assert(/action\?\.kind === "inspect_project_status"/.test(minimalAgentPanelSource), "read-only status inspection must be keyed by the Agent action kind");
assert(/localAction\.kind === "inspect_project_status"[\s\S]*stagedAction\.kind !== "inspect_project_status"[\s\S]*return localAction/.test(minimalAgentPanelSource), "local read-only status questions must not be downgraded into staged write actions by a mismatched App preview");
assert(/directorAgentReadinessActions\(readiness\)/.test(suggestedIntentFromStatusInspection), "status-inspection continue should use the Agent action path instead of hard-coded readiness branches");
assert(/priority === "now"[\s\S]*现在/.test(agentActionPathStepLabel), "Agent action path must label the immediate action in creator-facing language");
assert(/priority === "next"[\s\S]*接着/.test(agentActionPathStepLabel), "Agent action path must label the follow-up action in creator-facing language");
assert(/const readinessItems = directorAgentReadinessActions\(action\.sourceContext\.projectReadiness\)\.map/.test(agentActionPathItems), "Agent action path UI must render readiness actions from the Agent snapshot");
assert(/return \[\.\.\.qaActionItems,\s*\.\.\.readinessItems\]\.slice\(0,\s*3\)/.test(agentActionPathItems), "Agent action path UI must keep QA repair plus readiness actions bounded");
assert(/intent:\s*suggestedIntentFromStatusAction\(item\.label,\s*item\.reason\)/.test(agentActionPathItems), "each Agent action path item must carry the staged follow-up intent and reason");
assert(/agentStatusActionPath/.test(minimalAgentPanelSource), "Agent status action path must be projected into the panel");
assert(/aria-label="后续动作路径"/.test(minimalAgentPanelSource), "Agent status action path must have a dedicated visible region");
assert(/onClick=\{\(\) => void continueFromStatusActionPath\(item\.intent\)\}/.test(minimalAgentPanelSource), "clicking a status action path item must stage that specific next action");
assert(/closeReadOnlyAgentStatus\(\)[\s\S]*await prepareChange\(nextIntent\)/.test(continueFromStatusActionPath), "status action path clicks must return to composer state and stage a new plan");
assert(!/confirmPlan\(|runConfirmedAgentTool\(|onCreateP6RealSample|onSendSeedanceVideo|onRunExport/.test(continueFromStatusActionPath), "status action path clicks must not execute tools or submit generation");
assert(/agentActionIsStatusInspection\(action\)[\s\S]*return \[\]/.test(agentActionDiffs), "read-only project status inspections must not render staged diffs");
assert(/proposedChanges\.map/.test(agentStatusInspectionFacts), "read-only project status inspections should still render their status facts");
assert(/const displayedAgentToolHandoff = readOnlyStatusInspection \? undefined : agentToolHandoff/.test(minimalAgentPanelSource), "read-only project status inspections must not expose tool handoff facts");
assert(/readOnlyStatusInspection[\s\S]*\? \["项目状态", "只读"\]/.test(minimalAgentPanelSource), "read-only project status inspections must show status-only badges");
assert(/if\s*\(readOnlyStatusInspection\)\s*\{[\s\S]*label:\s*"继续"[\s\S]*void continueFromStatusInspection\(\)/.test(minimalAgentPanelSource), "read-only project status inspections must continue through the unified primary operation instead of asking for confirmation");
assert(/agentReviewPrimaryLabel\(agentActionEnvelope\)/.test(minimalAgentPanelSource), "review primary button must use the Agent action kind instead of one generic confirmation label");
assert(/action\.kind === "request_style_research"[\s\S]*确认查资料/.test(agentReviewPrimaryLabel), "web research staged actions must use a creator-facing research confirmation label");
assert(/action\.kind === "prepare_reference_generation"[\s\S]*确认生成参考/.test(agentReviewPrimaryLabel), "reference generation staged actions must use a creator-facing reference confirmation label");
assert(/action\.kind === "prepare_video_submit"[\s\S]*executionContract\.videoSubmitAllowed[\s\S]*确认发送[\s\S]*确认计划/.test(agentReviewPrimaryLabel), "video staged actions must distinguish plan-only planning from real submission");
assert(/action\.kind === "prepare_export"[\s\S]*确认导出/.test(agentReviewPrimaryLabel), "export staged actions must use a creator-facing export confirmation label");
assert(/action\.kind === "review_reference_asset"[\s\S]*确认复核/.test(agentReviewPrimaryLabel), "reference review staged actions must use a creator-facing review confirmation label");
assert(/action\.kind === "update_shot_strategy"[\s\S]*确认方式/.test(agentReviewPrimaryLabel), "shot mode edits must use a creator-facing mode confirmation label");
assert(/agentActionIsStatusInspection\(nextAgentActionEnvelope\)[\s\S]*\? "已检查项目状态"/.test(minimalAgentPanelSource), "read-only project status inspections must show a finished status after analysis");
assert(/function suggestedIntentFromStatusInspection/.test(minimalAgentPanelSource), "read-only project status inspections must provide a recommended next Agent intent");
assert(/nextCandidate\?\.label \|\| readiness\.nextActionLabel/.test(suggestedIntentFromStatusInspection), "status-inspection continuation must map readiness to the next creator-facing action");
assert(/async function prepareChange\(intentOverride\?: string\)/.test(minimalAgentPanelSource), "Agent composer must be able to stage a suggested next action without retyping");
assert(/const usingOverride = Boolean\(intentOverride\?\.trim\(\)\)/.test(prepareChange), "suggested next actions must bypass stale composer text and attachments");
assert(/function continueFromStatusInspection/.test(minimalAgentPanelSource), "read-only status inspections must be able to continue into the suggested staged action");
assert(/agentActionIsStatusInspection\(agentActionEnvelope\)[\s\S]*continueFromStatusInspection/.test(minimalAgentPanelSource), "status-inspection primary action should stage the recommended next step instead of only closing the panel");
assert(/function choosePreparedAgentAction/.test(minimalAgentPanelSource), "Agent composer must explicitly reconcile local command routing with staged LLM plans");
assert(/localAction\.kind !== stagedAction\.kind[\s\S]*isConcreteLocalAgentAction\(localAction\)[\s\S]*return localAction/.test(minimalAgentPanelSource), "explicit local tool intents must not be overwritten into ordinary shot edits");
assert(/aria-label="待确认改动"/.test(minimalAgentPanelSource), "Agent panel must show staged diffs before confirmation");
assert(/aria-label="待确认改动明细"/.test(minimalAgentPanelSource), "Agent details must retain full staged diffs");
assert(/aria-label="确认后动作"/.test(minimalAgentPanelSource), "Agent panel must show the post-confirmation action path before confirmation");
assert(/aria-label="AI 导演执行路径"/.test(minimalAgentPanelSource), "Agent panel must show a visible read-stage-write-tool trace");
assert(/minimal-agent-confirmation-strip/.test(minimalAgentPanelSource), "Agent confirmation facts must have a dedicated visible strip");
assert(/minimal-agent-execution-trace/.test(minimalAgentPanelSource), "Agent execution trace must have a dedicated visible strip");
assert(/label:\s*"写入"[\s\S]*agentConfirmedProjectWriteLabel/.test(agentActionConfirmationFacts), "confirmation strip must state project write behavior");
assert(/label:\s*"下一步"[\s\S]*agentNextControlledStepLabel/.test(agentActionConfirmationFacts), "confirmation strip must state the next controlled action");
assert(/label:\s*"范围"[\s\S]*targetScope/.test(agentActionConfirmationFacts), "confirmation strip must show the confirmed target scope");
assert(/label:\s*"边界"[\s\S]*agentExecutionModeLabel/.test(agentActionConfirmationFacts), "confirmation strip must show the generation boundary");
assert(/label:\s*"结果"[\s\S]*agentExpectedReceiptLabel/.test(agentActionConfirmationFacts), "confirmation strip must show the expected receipt before tool execution");
assert(/action\.target\.kind === "shot"[\s\S]*agentShotScopeLabel/.test(agentTargetScopeLabel), "pre-confirmation action scope must use the staged Agent target, not the unconfirmed handoff blocker");
assert(/action\.target\.kind === "multi_shot"[\s\S]*agentShotScopeLabel/.test(agentTargetScopeLabel), "pre-confirmation multi-shot scope must be creator-facing");
assert(/return agentTargetScopeLabel\(action\)/.test(agentActionScopeLabel), "action scope should fall back to the staged Agent target when no confirmed invocation exists");
assert(/planPhase === "confirmed"[\s\S]*已写入项目/.test(agentConfirmedProjectWriteLabel), "confirmed action facts must distinguish written project state");
assert(/sourceContext\.projectTitle/.test(agentExecutionTraceItems), "execution trace must show the project the Agent read");
assert(/projectRoot\?:\s*string/.test(directorAgentActionSource), "Agent action source context must carry project identity");
assert(/projectRoot:\s*input\.snapshot\.projectRoot/.test(directorAgentActionSource), "Agent action envelopes must remember the project root they were staged from");
assert(/agent_action_project_context_mismatch/.test(readText("src/agent/directorProductAgentLoop.ts")), "Product Agent loop must block stale actions from another project root");
assert(/agentActionScopeLabel\(action,\s*handoff,\s*planPhase\)/.test(agentExecutionTraceItems), "execution trace must show the Agent-selected scope");
assert(/agentConfirmedProjectWriteLabel\(action,\s*handoff,\s*planPhase\)/.test(agentExecutionTraceItems), "execution trace must show staged versus confirmed Project.vibe write state");
assert(/agentNextControlledStepLabel\(action,\s*handoff,\s*planPhase\)/.test(agentExecutionTraceItems), "execution trace must show the next controlled tool step");
assert(/planPhase === "confirmed"[\s\S]*handoff\?\.status === "blocked"[\s\S]*暂不执行/.test(agentNextControlledStepLabel), "blocked handoffs must only state no-tool after confirmation");
assert(/planPhase !== "confirmed"[\s\S]*handoff\?\.status === "blocked"[\s\S]*agentToolPreflightLabel/.test(agentNextControlledStepLabel), "pre-confirmation blocked handoffs must surface readiness blockers before confirmation");
assert(/action\.toolPlan\.toolName === "project_vibe_patch"[\s\S]*只写项目/.test(agentNextControlledStepLabel), "project patch staged actions must say they only write the project");
assert(/agentToolHandlerLabel\(action\.toolPlan\.toolName\)/.test(agentNextControlledStepLabel), "pre-confirmation next step should describe the planned controlled tool");
assert(/project_not_ready[\s\S]*需要本地项目/.test(agentToolPreflightLabel), "pre-confirmation handoff should show missing project before confirmation");
assert(/web_search_not_ready[\s\S]*先开启查资料/.test(agentToolPreflightLabel), "pre-confirmation handoff should show disabled web search before confirmation");
assert(/reference_generation_not_ready[\s\S]*先连接图片服务/.test(agentToolPreflightLabel), "pre-confirmation handoff should show unavailable reference generation before confirmation");
assert(/reference_generation_not_allowed[\s\S]*先整理/.test(agentToolPreflightLabel), "pre-confirmation handoff should show plan-only reference boundary before confirmation");
assert(/video_submit_not_ready[\s\S]*先准备视频/.test(agentToolPreflightLabel), "pre-confirmation handoff should show unavailable video submit before confirmation");
assert(/video_submit_not_allowed[\s\S]*当前不能发送/.test(agentToolPreflightLabel), "pre-confirmation handoff should show no-video boundary before confirmation");
assert(/export_not_ready[\s\S]*先准备导出/.test(agentToolPreflightLabel), "pre-confirmation handoff should show unavailable export before confirmation");
assert(/image_reference_receipt[\s\S]*参考已保存/.test(agentExpectedReceiptLabel), "expected receipt helper must expose Image2 review receipt before execution");
assert(/minimal-agent-diff/.test(stylesSource), "staged Agent diffs need dedicated styling");
assert(/minimal-agent-result-facts/.test(stylesSource), "confirmed Agent result facts need dedicated styling");
assert(/\.minimal-agent-confirmation-strip/.test(stylesSource), "post-confirmation action path needs dedicated styling");
assert(/\.minimal-agent-execution-trace/.test(stylesSource), "Agent execution trace needs dedicated styling");
assert(/\.minimal-agent-execution-trace small\.blocked/.test(stylesSource), "Agent execution trace must distinguish blocked steps");
assert(/\.minimal-agent-action-path/.test(stylesSource), "Agent status action path needs dedicated styling");
assert(/\.minimal-agent-action-path button\.now/.test(stylesSource), "Agent status action path must visually distinguish the immediate action");
assert(/\.minimal-agent-action-path button:focus-visible/.test(stylesSource), "Agent status action path buttons must keep a visible keyboard focus state");
assert(/buildDirectorAgentToolHandoff\(\{/.test(buildConfirmedAgentToolHandoff), "confirmed Agent actions must build a controlled tool handoff");
assert(/availability:\s*currentAgentToolAvailability\(\)/.test(buildConfirmedAgentToolHandoff), "confirmed Agent handoff must reuse the same live tool availability as staging");
assert(/projectReady:\s*localProjectReadyForTools/.test(currentAgentToolAvailability), "project readiness shown to Agent tools must use the local project folder gate");
assert(/webSearchReady:\s*effectiveWebSearchReady/.test(currentAgentToolAvailability), "web search handoff must respect resolved settings and credential readiness");
assert(/const referenceGenerationReady = Boolean\(/.test(currentAgentToolAvailability), "reference handoff must compute an explicit readiness gate");
assert(/localProjectReadyForTools[\s\S]*onCreateP6RealSample[\s\S]*realSampleAction\.keyConfigured[\s\S]*!realSampleAction\.disabled[\s\S]*!realSampleBusy/.test(currentAgentToolAvailability), "reference handoff must require a local project plus configured and enabled generation");
assert(/referenceGenerationReady,/.test(currentAgentToolAvailability), "reference handoff must pass the computed readiness gate");
assert(/videoSubmitReady:\s*Boolean\(localProjectReadyForTools[\s\S]*onSendSeedanceVideo[\s\S]*videoSendAction\?\.ready/.test(currentAgentToolAvailability), "video submission must require a local project before a provider handoff is available");
assert(/exportReady:\s*Boolean\(localProjectReadyForTools[\s\S]*onRunExport/.test(currentAgentToolAvailability), "export handoff must require a local project");
assert(/videoSubmitReady:\s*Boolean\(localProjectReadyForTools[\s\S]*onSendSeedanceVideo/.test(currentAgentToolAvailability), "video handoff must require a local project and the session submit action");
assert(/exportReady:\s*Boolean\(localProjectReadyForTools[\s\S]*onRunExport/.test(currentAgentToolAvailability), "export handoff must require a local project and the export action");
assert(/preparedHandoff\s*\|\|\s*buildConfirmedAgentToolHandoff\(action\)/.test(runConfirmedAgentTool), "tool execution must reuse the persisted handoff when available");
assert(/handoff\.status === "handled_by_project_write"[\s\S]*return \{ status: "completed"[\s\S]*修改已写入项目/.test(runConfirmedAgentTool), "project-write handoffs must complete without being treated as blocked tool failures");
assert(/agentToolHandoffBindingIssue\(action,\s*handoff\)/.test(runConfirmedAgentTool), "tool execution must reject stale or mismatched Agent handoffs before calling tools");
assert(/这次动作已经变化，请重新发送一次/.test(agentToolHandoffBindingIssue), "stale handoffs must produce a creator-facing retry message");
assert(/handoff\.actionId !== action\.actionId/.test(agentToolHandoffBindingIssue), "handoff binding guard must check action id");
assert(/handoff\.handler !== action\.toolPlan\.toolName/.test(agentToolHandoffBindingIssue), "handoff binding guard must check tool handler");
assert(/handoff\.expectedReceipt !== action\.toolPlan\.expectedReceipt/.test(agentToolHandoffBindingIssue), "handoff binding guard must check expected receipt");
assert(/taskEnvelope\.providerSubmitAllowed !== action\.toolPlan\.providerSubmitAllowed/.test(agentToolHandoffBindingIssue), "handoff binding guard must check provider policy");
assert(/agentToolBlockedStatus\(handoff\)/.test(runConfirmedAgentTool), "blocked tool handoff must produce an actionable status");
assert(/const invocation = handoff\.invocation/.test(runConfirmedAgentTool), "ready tool execution must use the Product-Agent invocation payload");
assert(/if \(!invocation\)[\s\S]*动作缺少确认后的执行信息/.test(runConfirmedAgentTool), "ready tool execution must block when the confirmed invocation payload is missing");
assert(/buildDirectorAgentToolTrace\(action,\s*handoff\)/.test(runConfirmedAgentTool), "ready tool execution must build the shared controlled tool trace");
assert(/if \(!toolTraceResult\.ok \|\| !toolTraceResult\.trace\)/.test(runConfirmedAgentTool), "ready tool execution must block when the traceable tool record is missing");
assert(/const agentToolTrace = toolTraceResult\.trace/.test(runConfirmedAgentTool), "controlled tool execution must pass the shared Agent tool trace to runtime tools");
assert(/type AgentControlledToolInvocationTarget[\s\S]*agentToolTrace\?:\s*DirectorAgentToolTrace/.test(agentPanelProjectionSource), "controlled Agent tool targets must use the shared trace type");
assert(/type AgentControlledToolInvocationTarget[\s\S]*videoPermissionContract\?:\s*AgentVideoSubmitContract/.test(agentPanelProjectionSource), "controlled Agent tool targets must carry the session video permission contract");
assert(/type AgentControlledToolInvocationTarget[\s\S]*scope\?:\s*"project" \| "selected_shots"/.test(agentPanelProjectionSource), "controlled Agent tool targets must support explicit project-level scope");
assert(/const toolUserIntent = invocation\.userIntent \|\| userIntent/.test(runConfirmedAgentTool), "tool execution must prefer the confirmed invocation user intent");
assert(/buildDirectorResearchQuery\(toolUserIntent\)/.test(runConfirmedAgentTool), "web search must compile its query from the confirmed invocation payload");
assert(/requestAgentWebSearch\(\{[\s\S]*agentToolTrace,/.test(runConfirmedAgentTool), "web search must carry the Agent tool trace into the runtime request");
assert(/const result = await onCreateP6RealSample\?\.\(\{[\s\S]*selectedShotIds:\s*invocation\.selectedShotIds[\s\S]*skipConfirm:\s*true[\s\S]*confirmationReceiptId:\s*handoff\.handoffId[\s\S]*confirmedAt:\s*invocation\.confirmation\.confirmedAt/.test(runConfirmedAgentTool), "reference generation must execute against the confirmed Agent-selected shots and reuse the Agent confirmation receipt");
assert(/onCreateP6RealSample\?\.\(\{[\s\S]*agentToolTrace,/.test(runConfirmedAgentTool), "reference generation must carry the Agent tool trace into the runtime request");
assert(/selectedAssetId:\s*invocation\.selectedAssetId/.test(runConfirmedAgentTool), "reference generation must preserve the confirmed Agent-selected asset scope");
assert(/sectionId:\s*invocation\.sectionId/.test(runConfirmedAgentTool), "reference generation must preserve the confirmed Agent-selected section scope");
assert(/referenceGenerationToolOutcome\(result\)/.test(runConfirmedAgentTool), "reference generation must convert the real tool result into Agent-facing status");
assert(/const result = await onSendSeedanceVideo\?\.\(\{[\s\S]*selectedShotIds:\s*invocation\.selectedShotIds[\s\S]*skipConfirm:\s*true[\s\S]*confirmationReceiptId:\s*handoff\.handoffId[\s\S]*confirmedAt:\s*invocation\.confirmation\.confirmedAt/.test(runConfirmedAgentTool), "video submit must execute against the confirmed Agent-selected shots and reuse the Agent confirmation receipt");
assert(/onSendSeedanceVideo\?\.\(\{[\s\S]*agentToolTrace,/.test(runConfirmedAgentTool), "video submit must carry the Agent tool trace into the runtime request");
assert(/onSendSeedanceVideo\?\.\(\{[\s\S]*videoPermissionContract:\s*activeVideoPermissionContract/.test(runConfirmedAgentTool), "video submit must carry the visible session permission contract into the runtime request");
assert(/selectedAssetId:\s*invocation\.selectedAssetId/.test(runConfirmedAgentTool), "video submit must preserve the confirmed Agent-selected asset scope");
assert(/sectionId:\s*invocation\.sectionId/.test(runConfirmedAgentTool), "video submit must preserve the confirmed Agent-selected section scope");
assert(/videoSubmitToolOutcome\(result\)/.test(runConfirmedAgentTool), "video submit must convert the real tool result into Agent-facing status");
assert(/function exportToolOutcome/.test(minimalAgentPanelSource), "export handoff must convert the real export result into Agent-facing status");
assert(/const result = await onRunExport\?\.\(\{\s*agentToolTrace\s*\}\)/.test(runConfirmedAgentTool), "export handoff must capture the real export action result with the Agent tool trace");
assert(/exportToolOutcome\(result\)/.test(runConfirmedAgentTool), "export handoff must use the structured export outcome");
assert(/项目已保留/.test(runConfirmedAgentTool), "tool execution failure should say the project record is preserved");
assert(/Promise<ConfirmedAgentToolRunOutcome>/.test(minimalAgentPanelSource), "controlled tool execution must return a structured outcome");
assert(/return \{ status: "failed"[\s\S]*projectRecordPreserved: true \}/.test(runConfirmedAgentTool), "controlled tool execution failures must return a failed outcome instead of being swallowed");
assert(/const authoritativeAgentToolHandoff = previewResult\?\.agentToolHandoff \|\| confirmedAgentToolHandoff/.test(minimalAgentPanelSource), "UI must prefer the App/Product-Agent returned handoff over the locally precomputed handoff");
assert(/const authoritativeAgentActionEnvelope = previewResult\?\.agentActionEnvelope \|\| agentActionEnvelope/.test(minimalAgentPanelSource), "UI must prefer the App/Product-Agent returned action over the locally precomputed action");
assert(/setAgentActionEnvelope\(authoritativeAgentActionEnvelope\)/.test(minimalAgentPanelSource), "UI must keep the confirmed Product-Agent action envelope for result traces and retries");
assert(/runConfirmedAgentTool\(authoritativeAgentActionEnvelope,\s*userIntent,\s*authoritativeAgentToolHandoff\)/.test(minimalAgentPanelSource), "tool execution must use the authoritative returned action and handoff");
assert(/const toolRunOutcome = await runConfirmedAgentTool\(authoritativeAgentActionEnvelope,\s*userIntent,\s*authoritativeAgentToolHandoff\)/.test(minimalAgentPanelSource), "preview confirmation must capture the controlled tool execution outcome");
assert(/const confirmedRun = confirmedToolRunResult\(authoritativeAgentToolHandoff,\s*toolRunOutcome,\s*previewResult(?:\s*\|\|\s*undefined)?\)[\s\S]*setLocalPrototypeAgentDemo\(confirmedRun\)/.test(minimalAgentPanelSource), "tool handoff completion must reflect the actual controlled tool outcome and Project.vibe summary");
assert(/agentToolHandoff:\s*confirmedAgentToolHandoff/.test(minimalAgentPanelSource), "preview handoff must carry the confirmed Agent tool handoff");
assert(/async function retryConfirmedAgentTool/.test(minimalAgentPanelSource), "confirmed Agent tool runs need a retry path");
assert(/agentToolHandoff\.status === "blocked"[\s\S]*buildConfirmedAgentToolHandoff\(agentActionEnvelope\)/.test(retryConfirmedAgentTool), "retry must refresh blocked handoffs after settings or availability changes");
assert(/runConfirmedAgentTool\(agentActionEnvelope,\s*userIntent,\s*refreshedHandoff\)/.test(retryConfirmedAgentTool), "retry must use the confirmed Agent action and refreshed controlled handoff");
assert(/const retryRun = confirmedToolRunResult\(refreshedHandoff,\s*toolRunOutcome\)[\s\S]*setLocalPrototypeAgentDemo\(retryRun\)/.test(retryConfirmedAgentTool), "retry outcome must be reflected through the same structured result projection");
assert(/重试失败，项目已保留/.test(retryConfirmedAgentTool), "retry failures must preserve the project-record guarantee");
assert(/const canRetryConfirmedTool = Boolean/.test(minimalAgentPanelSource), "confirmed result note must gate tool retry visibility");
assert(/const confirmedResultBlocked = Boolean/.test(minimalAgentPanelSource), "confirmed result note must share a blocked/error signal");
assert(/const agentResultTarget = confirmedResultBlocked \? undefined : agentResultViewTarget\(agentToolHandoff\)/.test(minimalAgentPanelSource), "failed or blocked confirmed results must not expose result navigation");
assert(/&& confirmedResultBlocked/.test(minimalAgentPanelSource), "retry visibility must use the same blocked/error signal as result navigation");
assert(/agentToolHandoff\.status !== "handled_by_project_write"/.test(minimalAgentPanelSource), "project-only writes should not expose a tool retry button");
assert(/prototypeAgentDemo\?\.status === "error"/.test(minimalAgentPanelSource), "tool retry should be available after failed confirmed tool runs");
assert(/onClick=\{retryConfirmedAgentTool\}[\s\S]*再试一次/.test(minimalAgentPanelSource), "confirmed result note must expose a retry button for failed tools");
assert(/onClick=\{openAgentResultView\}[\s\S]*agentResultTarget\.label/.test(minimalAgentPanelSource), "confirmed result note must expose a direct result-view button");
assert(/onClick=\{revisePlan\}[\s\S]*继续修改/.test(minimalAgentPanelSource), "confirmed result note must offer a direct continue-edit path");
assert(/async function inspectNextAfterConfirmedAction/.test(minimalAgentPanelSource), "confirmed result note must provide a fresh project-status continuation path");
assert(/setPlanPhase\("idle"\)/.test(inspectNextAfterConfirmedAction), "fresh next-step inspection must leave the old confirmed result state");
assert(/prepareChange\("现在项目怎么样"\)/.test(inspectNextAfterConfirmedAction), "fresh next-step inspection must re-read the current project state");
assert(/onClick=\{inspectNextAfterConfirmedAction\}[\s\S]*检查下一步/.test(minimalAgentPanelSource), "confirmed result note must expose the fresh next-step inspection button");
assert(/async function continueNextAfterConfirmedAction/.test(minimalAgentPanelSource), "confirmed result note must provide a direct next staged-action path");
assert(/setPlanPhase\("idle"\)/.test(continueNextAfterConfirmedAction), "direct next-step continuation must leave the old confirmed result state");
assert(/prepareChange\("下一步"\)/.test(continueNextAfterConfirmedAction), "direct next-step continuation must re-read project state and stage the next action");
assert(!/confirmPlan\(\)/.test(continueNextAfterConfirmedAction), "direct next-step continuation must not confirm or execute the next action automatically");
assert(/onClick=\{continueNextAfterConfirmedAction\}[\s\S]*继续下一步/.test(minimalAgentPanelSource), "confirmed result note must expose the direct next staged-action button");
assert(/onVideoPermissionContractChange\?\.\(nextContract\)/.test(updateVideoPermissionContract), "MinimalAgentPanel must expose contract updates to the session owner");
assert(/availability\.projectReady[\s\S]*projectStatusLabel[\s\S]*需要本地项目/.test(agentCapabilityItems), "Agent capability list must surface project readiness and browser-draft status copy");
assert(/availability\.webSearchReady[\s\S]*设置里开启/.test(agentCapabilityItems), "Agent capability list must surface web-search readiness without provider wording");
assert(/contract\.referenceGenerationAllowed[\s\S]*先整理[\s\S]*!localProjectReady[\s\S]*先保存项目[\s\S]*availability\.referenceGenerationReady/.test(agentCapabilityItems), "Agent capability list must respect reference-generation boundary, local project readiness, and provider readiness");
assert(/contract\.videoSubmitAllowed[\s\S]*等你允许[\s\S]*!localProjectReady[\s\S]*先保存项目[\s\S]*availability\.videoSubmitReady/.test(agentCapabilityItems), "Agent capability list must respect video-submission boundary, local project readiness, and provider readiness");
assert(/!localProjectReady \? "先保存项目" : availability\.exportReady/.test(agentCapabilityItems), "Agent capability list must not call export ready before a local project exists");
assert(/const projectNeededForGeneratedStory = !localProjectReadyForTools[\s\S]*runtimeState\.storyFlow\.shots\.length > 0[\s\S]*runtimeState\.visualMemory\.summary\.missing > 0/.test(minimalAgentPanelSource), "bottom Agent composer must detect when a browser draft has become a real story that needs a local project before generation");
assert(/const projectNeedsLocalFolder = !localProjectReadyForTools[\s\S]*Boolean\(footerDirectAction\) \|\| projectNeededForGeneratedStory/.test(minimalAgentPanelSource), "bottom Agent composer must treat generated browser stories as local-project-required workflow");
assert(/const projectRequiredForWorkflow = projectNeedsLocalFolder && \(canCreateProjectFromFooter \|\| localProjectBusy\)/.test(minimalAgentPanelSource), "bottom Agent composer must offer local project creation when a generated story is ready for generation");
assert(/if \(projectRequiredForWorkflow\)[\s\S]*label = projectRequirement\.label[\s\S]*perform: \(\) => \{[\s\S]*onCreateLocalProject\?\.\(\)/.test(minimalAgentPanelSource), "bottom Agent composer must turn the single primary action into local project creation instead of a dead send button");
assert(/if \(projectBlockedWithoutFooterResolver\)[\s\S]*label: "发送"[\s\S]*disabled:\s*true[\s\S]*生成参考、视频或导出前需要本地项目/.test(minimalAgentPanelSource), "bottom Agent composer must not replace the main send entry with a project action when local project controls are unavailable");
assert(/const footerPrimaryUsesAgentNext = \(!hasComposerInput[\s\S]*primaryLabel !== "发送"/.test(minimalAgentPanelSource), "empty-composer next actions must be folded into the single bottom primary button");
assert(/function handleSend\(\)[\s\S]*void prepareChange\(\)/.test(minimalAgentPanelSource), "fixed send button must route typed text or attachments through the Agent planner");
assert(/className="minimal-agent-send-button"[\s\S]*onClick=\{hasComposerInput && !composerInputUsesNextAction \? handleSend : handleNext\}/.test(minimalAgentPanelSource), "bottom composer must render one primary control that sends new text or continues recognized next-action intent");
assert(!/className="minimal-agent-suggested-button"/.test(minimalAgentPanelSource), "bottom composer must not render a second suggested-action button");
assert(/aria-label="现在能做"/.test(minimalAgentPanelSource), "Agent details must show a compact current capability list");
assert(/visibleAgentCapabilityItems\.map/.test(minimalAgentPanelSource), "Agent capability list must be rendered from live availability");
assert(/const attentionItems = items\.filter\(\(item\) => item\.tone !== "ready"\)/.test(agentCapabilityGlanceItems), "Agent capability glance should prioritize blocked or waiting capabilities");
assert(/attentionItems\.length \? attentionItems : items\.filter\(\(item\) => item\.id !== "project"\)/.test(agentCapabilityGlanceItems), "Agent capability glance should show useful ready actions when nothing needs attention");
assert(/slice\(0,\s*3\)/.test(agentCapabilityGlanceItems), "Agent capability glance must stay compact");
assert(/visibleAgentCapabilityGlanceItems = agentCapabilityGlanceItems\(visibleAgentCapabilityItems\)/.test(minimalAgentPanelSource), "Agent capability glance must be derived from the same live availability as the detail list");
assert(/aria-label="AI 导演当前能力"/.test(minimalAgentPanelSource), "Agent capability glance must be visible outside the hidden details panel");
assert(/visibleAgentCapabilityGlanceItems\.map/.test(minimalAgentPanelSource), "Agent capability glance must render live readiness chips");
assert(/\.minimal-agent-capabilities/.test(stylesSource), "Agent capability list needs dedicated styling");
assert(/\.minimal-agent-capability-strip/.test(stylesSource), "Agent capability glance needs dedicated styling");
assert(/type AgentControlledToolInvocationTarget[\s\S]*selectedAssetId\?:\s*string[\s\S]*sectionId\?:\s*string/.test(agentPanelProjectionSource), "controlled Agent tool targets must carry selected asset and section scope");
assert(/type AgentControlledToolInvocationTarget[\s\S]*agentToolTrace\?:/.test(agentPanelProjectionSource), "controlled Agent tool targets must carry the traceable tool record");
assert(/agentTaskEnvelope:\s*options\?\.agentToolTrace/.test(image2AssetActionSource), "Agent-triggered Image2 reference generation must send the internal task record to the runtime route");
assert(/agentTaskEnvelope:\s*options\?\.agentToolTrace/.test(seedanceVideoSubmitActionSource), "Agent-triggered video submit must send the internal task record to the runtime route");
assert(/selectedAssetId:\s*options\.selectedAssetId/.test(image2AssetActionSource), "Agent-triggered Image2 reference generation must pass selected asset scope into target resolution");
assert(/sectionId:\s*options\.sectionId/.test(image2AssetActionSource), "Agent-triggered Image2 reference generation must pass selected section scope into target resolution");
assert(/shotIdsForAsset\(input\.runtimeState,\s*input\.selectedAssetId\)/.test(scopedAssetGenerationTarget), "Image2 reference generation must resolve selected assets to bound shots");
assert(/shotIdsForSection\(input\.runtimeState,\s*input\.sectionId\)/.test(scopedAssetGenerationTarget), "Image2 reference generation must resolve selected sections to shot ids");
assert(/input\.scope === "project"[\s\S]*assetGenerationTarget\(undefined,\s*undefined\)/.test(scopedAssetGenerationTarget), "Image2 reference generation must preserve explicit project-level scope");
assert(/这个素材还没有绑定到镜头/.test(scopedAssetGenerationTarget), "Image2 reference generation must block unresolved asset-only scope instead of silently running the full project");
assert(/selectedAssetId:\s*options\.selectedAssetId/.test(seedanceVideoSubmitActionSource), "Agent-triggered video submit must pass selected asset scope into target resolution");
assert(/sectionId:\s*options\.sectionId/.test(seedanceVideoSubmitActionSource), "Agent-triggered video submit must pass selected section scope into target resolution");
assert(/shotIdsForAsset\(input\.runtimeState,\s*input\.selectedAssetId\)/.test(scopedVideoShotIds), "video submit must resolve selected assets to bound shots");
assert(/shotIdsForSection\(input\.runtimeState,\s*input\.sectionId\)/.test(scopedVideoShotIds), "video submit must resolve selected sections to shot ids");
assert(/这个段落还没有可发送的镜头/.test(scopedVideoShotIds), "video submit must block unresolved section scope instead of silently submitting the full project");
assert(/useState<DirectorAgentActionEnvelope \| undefined>/.test(minimalAgentPanelSource), "MinimalAgentPanel must keep the current staged action envelope");
assert(/useState<DirectorAgentToolHandoff \| undefined>/.test(minimalAgentPanelSource), "MinimalAgentPanel must keep the current tool handoff");
assert(/previousRuntimeProjectKeyRef = useRef\(""\)/.test(minimalAgentPanelSource), "MinimalAgentPanel must track project identity for staged Agent state");
assert(/const runtimeProjectKey = \[[\s\S]*runtimeState\.project\.root[\s\S]*runtimeState\.sourceIndexSummary\.projectId/.test(minimalAgentPanelSource), "staged Agent state must be scoped to the current project identity");
assert(/previousRuntimeProjectKeyRef\.current === runtimeProjectKey\) return;[\s\S]*setWorkflow\(undefined\)[\s\S]*setPreparedContext\(undefined\)[\s\S]*setAgentActionEnvelope\(undefined\)[\s\S]*setAgentToolHandoff\(undefined\)[\s\S]*项目已切换，重新发送即可/.test(minimalAgentPanelSource), "switching projects must clear stale staged Agent plans and handoffs before confirmation");
assert(/agentActionEnvelope\?\.status === "blocked"/.test(minimalAgentPanelSource), "blocked staged actions must disable confirmation");
assert(/action\.status === "blocked"[\s\S]*return "需要补充"/.test(agentReviewPrimaryLabel), "blocked staged actions must show a creator-facing blocked button label");
assert(/actionBlocked && agentActionEnvelope[\s\S]*agentActionEnvelope\.userFacingMessage/.test(minimalAgentPanelSource), "blocked staged actions must expose the concrete Agent blocker as the disabled button reason");
assert(/if\s*\(\s*primaryDisabled\s*\)[\s\S]*setStatus\(primaryDisabledReason\)[\s\S]*return;/.test(handleNext), "primary action handler must not bypass disabled confirmation state");
assert(/继续点下方「\{primaryLabel\}」/.test(minimalAgentPanelSource), "staged Agent cards must point to the bottom composer action instead of rendering a second primary action");
assert(!/<button disabled=\{primaryDisabled\}[\s\S]*\{primaryLabel\}[\s\S]*<\/button>/.test(minimalAgentPanelSource), "staged Agent cards must not duplicate the bottom primary button");
assert(/if\s*\(composerPrimaryIsFresh\)\s*\{[\s\S]*void prepareChange\(\)/.test(minimalAgentPanelSource), "typing into the bottom composer must start a fresh request through the unified primary operation instead of re-confirming the old action");
assert(/isPreparingPlan[\s\S]*status \|\| "正在整理"[\s\S]*稍等一下/.test(minimalAgentPanelSource), "disabled composer action should explain the current preparation state instead of a generic blocker");
assert(/const composerPrimaryIsFresh = hasComposerInput \|\| !workflow \|\| planPhase === "idle" \|\| planPhase === "confirmed"/.test(minimalAgentPanelSource), "fresh input and confirmed Agent results must show the bottom composer send action as a fresh entry point");
assert(/const footerPrimaryLabel = hasComposerInput && !composerInputUsesNextAction[\s\S]*footerPrimaryUsesAgentNext[\s\S]*primaryLabel/.test(minimalAgentPanelSource), "bottom composer primary button must stay visible and adapt between send, continue, and next-action states");
assert(/event\.preventDefault\(\);[\s\S]*hasComposerInput && !composerInputUsesNextAction\) handleSend\(\);[\s\S]*else handleNext\(\);/.test(minimalAgentPanelSource), "Cmd Enter should send fresh text or reuse the primary next-action handler so disabled states show their reason");
assert(/blocker !== "user_confirmation_required"/.test(agentToolHasPreflightBlocker), "pre-confirmation tool blockers must ignore the normal confirmation-required blocker");
assert(/const handoffPreflightBlocked = planPhase !== "confirmed" && agentToolHasPreflightBlocker\(displayedAgentToolHandoff,\s*agentActionEnvelope\)/.test(minimalAgentPanelSource), "confirmation gating must detect visible tool readiness blockers before the user confirms");
assert(/const confirmationBlocked = Boolean\(actionBlocked \|\| handoffPreflightBlocked\)/.test(minimalAgentPanelSource), "confirmation gating must combine Agent action and tool-readiness blockers");
assert(/confirmationBlocked \|\| \(!canConfirm && !canPreviewPrototypeDemo && !canConfirmFeedback\)/.test(minimalAgentPanelSource), "primary confirmation button must disable when tool preflight is blocked");
assert(/handoffPreflightBlocked && displayedAgentToolHandoff[\s\S]*agentToolPreflightLabel\(displayedAgentToolHandoff\)/.test(minimalAgentPanelSource), "disabled confirmation button should explain the visible tool readiness blocker");
assert(/先保存项目，再执行动作/.test(agentToolRecordLabel), "handoff facts should explain project-first tool execution");
assert(/确认后写项目/.test(agentToolRecordLabel), "confirmation-only handoffs should not look like a failed tool run");
assert(/已保存计划，动作未开始/.test(agentToolRecordLabel), "blocked handoff facts should explain that the tool did not run");
assert(/user_confirmation_required/.test(agentToolOnlyNeedsConfirmation), "confirmation-only handoffs should be separated from real blockers");
assert(/image2_reference_generation[\s\S]*确认后图片进复核/.test(agentToolPlannedResultLabel), "pre-confirmation Image2 handoffs should preview the expected review lane");
assert(/seedance_video_submit[\s\S]*确认后排队回预览/.test(agentToolPlannedResultLabel), "pre-confirmation video handoffs should preview the expected queue lane");
assert(/agentToolOnlyNeedsConfirmation\(handoff\)[\s\S]*agentToolPlannedResultLabel/.test(agentToolResultLabel), "handoff result facts should show the planned result when only user confirmation is pending");
assert(/图片先进入复核/.test(agentToolResultLabel), "Image2 reference handoff should explain review-first output");
assert(/排队后回到预览/.test(agentToolResultLabel), "Seedance handoff should explain preview return");
assert(/handoff\.invocation\?\.selectedShotIds/.test(agentToolScopeLabel), "handoff facts must show the confirmed invocation target scope");
assert(/handoff\.invocation\?\.targetSummary\.label/.test(agentToolScopeLabel), "handoff facts must use the self-describing invocation target summary when no explicit shots exist");
assert(/formatShotNumber/.test(agentShotScopeLabel), "handoff scope should use creator-facing shot numbers");
assert(/agentTargetScopeLabel\(action\)/.test(agentToolScopeLabel), "pre-confirmation handoff facts must fall back to the staged Agent target instead of saying the whole project");
assert(/agentExpectedReceiptLabel\(handoff\.expectedReceipt\)/.test(agentToolReceiptLabel), "tool receipt labels should use the shared expected-receipt helper");
assert(/handled_by_project_write[\s\S]*回到当前镜头检查/.test(agentToolFollowUpLabel), "project-only handoffs should route users back to the edited shot");
assert(/status === "blocked"[\s\S]*调整后可重试/.test(agentToolFollowUpLabel), "blocked handoffs should say the creator can retry after adjusting");
assert(/handler === "web_search"[\s\S]*保存为参考后再用/.test(agentToolFollowUpLabel), "web search handoffs should point to saved references");
assert(/handler === "image2_reference_generation"[\s\S]*去参考区复核/.test(agentToolFollowUpLabel), "reference generation handoffs should point to reference review");
assert(/handler === "seedance_video_submit"[\s\S]*等视频结果/.test(agentToolFollowUpLabel), "video submit handoffs should point to preview return");
assert(/handler === "project_export"[\s\S]*去交付页查看/.test(agentToolFollowUpLabel), "export handoffs should point to delivery review");
assert(/参考已保存/.test(agentExpectedReceiptLabel), "Image2 reference handoff should expose a review receipt lane");
assert(/视频已留档/.test(agentExpectedReceiptLabel), "Seedance handoff should expose a video submit receipt lane");
assert(/label:\s*"项目"[\s\S]*agentToolRecordLabel/.test(minimalAgentPanelSource), "handoff facts should use creator-facing project record wording");
assert(/label:\s*"动作"[\s\S]*agentToolHandlerLabel/.test(minimalAgentPanelSource), "handoff facts should show the controlled tool type");
assert(/label:\s*"范围"[\s\S]*agentToolScopeLabel/.test(minimalAgentPanelSource), "handoff facts should show the confirmed tool target scope");
assert(/label:\s*"结果"[\s\S]*agentToolResultLabel/.test(minimalAgentPanelSource), "handoff facts should show the expected result lane");
assert(/label:\s*"结果"[\s\S]*agentToolReceiptLabel/.test(minimalAgentPanelSource), "handoff facts should show the expected receipt lane");
assert(/const stagedProjectFacts =/.test(minimalAgentPanelSource), "staged Agent plans must expose Project.vibe impact facts before confirmation");
assert(/preparedContext\?\.projectRecordLabel[\s\S]*label:\s*"结果"/.test(minimalAgentPanelSource), "staged Project.vibe record summary must be visible in the plan details");
assert(/preparedContext\?\.projectImpactLabel[\s\S]*label:\s*"影响"/.test(minimalAgentPanelSource), "staged Project.vibe impact summary must be visible in the plan details");
assert(/preparedContext\?\.projectTaskLabel[\s\S]*label:\s*"待处理"/.test(minimalAgentPanelSource), "staged Project.vibe task summary must be visible in the plan details");
assert(/qaFeedbackFacts\(preparedContext\?\.qaFeedback\)/.test(minimalAgentPanelSource), "staged QA feedback must be visible in the plan details");
assert(/preparedContext\?\.qaFeedback\?\.summary/.test(minimalAgentPanelSource), "blocked staged actions must surface QA summary in the Agent understanding");
assert(/preparedContext\?\.qaFeedback\?\.primaryAction/.test(minimalAgentPanelSource), "blocked staged actions must surface QA primary action as next step");
assert(/const pack = await onSaveResearchAsReference/.test(minimalAgentPanelSource), "saving web research should capture the saved project reference pack");
assert(/本片参考已保存，后续整理会使用/.test(minimalAgentPanelSource), "saving web research should give a clear saved-to-project status");
assert(/projectRecordLabel:\s*"新增本片参考"/.test(minimalAgentPanelSource), "saved research should surface the project record summary");
assert(/projectImpactLabel:\s*"分镜、提示词和文本复核"/.test(minimalAgentPanelSource), "saved research should explain where it will be used");
assert(/projectTaskLabel:\s*pack\?\.title \|\| "已加入项目参考"/.test(minimalAgentPanelSource), "saved research should surface the saved reference title");

assert(/export type AgentVideoSubmitContract/.test(agentPanelProjectionSource), "agentPanelProjection must define the session contract type");
assert(/defaultAgentVideoSubmitContract[\s\S]*mode:\s*"plan_only"[\s\S]*videoSubmitAllowed:\s*false[\s\S]*referenceGenerationAllowed:\s*false[\s\S]*默认先整理/.test(agentPanelProjectionSource), "Agent session must default to plan-only until the creator explicitly opens generation");
assert(/videoAllowedAgentVideoSubmitContract[\s\S]*mode:\s*"video_allowed"[\s\S]*videoSubmitAllowed:\s*true[\s\S]*referenceGenerationAllowed:\s*true/.test(agentPanelProjectionSource), "video-allowed mode must stay available as an explicit creator boundary");
assert(/detectDirectorAgentPermissionIntent/.test(agentPanelProjectionSource), "Agent panel contract detection must use the shared permission intent classifier");
assert(/videoSubmitAllowed:\s*false/.test(detectVideoContract), "plan-only detection must write videoSubmitAllowed=false");
assert(/referenceGenerationAllowed:\s*false/.test(detectVideoContract), "plan-only detection must lock reference generation too");
assert(/mode:\s*"reference_allowed"[\s\S]*videoSubmitAllowed:\s*false[\s\S]*referenceGenerationAllowed:\s*true/.test(detectVideoContract), "no-video detection should still allow reference generation");
for (const phrase of ["先不要生图", "不生图", "不生图不提交视频", "不走生图生视频", "不跑生图生视频", "只拆分镜", "只规划", "只做计划"]) {
  assert(directorAgentPermissionIntentSource.includes(phrase), `plan-only phrases must include ${phrase}`);
}
for (const phrase of ["不要生成参考", "先不要生成参考", "不要做参考图", "先不要补参考", "先别补参考图"]) {
  assert(directorAgentPermissionIntentSource.includes(phrase), `no-reference-generation phrases must include ${phrase}`);
}
for (const phrase of ["先不要提交视频", "先不要提交视频测试", "先不提交视频", "不提交视频", "不要生视频", "先别提交", "先不跑视频", "先不用跑视频", "视频先不用跑", "视频先不用管", "不提交到即梦", "跑到视频前"]) {
  assert(directorAgentPermissionIntentSource.includes(phrase), `no-video phrases must include ${phrase}`);
}
for (const phrase of ["不要真实生图", "只看规划", "只跑文本", "跑到生图前"]) {
  assert(directorAgentPermissionIntentSource.includes(phrase), `plan-only control phrases must include ${phrase}`);
}
for (const phrase of ["可做参考", "可以做参考", "允许做参考", "可生成参考", "可以生成参考", "允许生成参考", "只补参考图"]) {
  assert(directorAgentPermissionIntentSource.includes(phrase), `reference boundary phrases must include ${phrase}`);
}
assert(/function isDirectorAgentPermissionControlOnlyIntent/.test(directorAgentPermissionIntentSource), "pure Agent boundary commands need a shared control-only classifier");
assert(/isDirectorAgentPermissionControlOnlyIntent\(userIntent\)[\s\S]*resetPreparedComposerState\(agentVideoPermissionLabel\(nextActionVideoPermissionContract\)\)[\s\S]*setText\(""\)[\s\S]*setAttachments\(\[\]\)[\s\S]*return;/.test(prepareChange), "pure Agent boundary commands should update the execution boundary without staging a Project.vibe edit");
assert(/agentVideoSubmitContractAllowsReference/.test(agentPanelProjectionSource), "session contract must expose reference-generation permission");
assert(/可做参考[\s\S]*可发视频/.test(labelVideoContract), "mode labels must include reference and video states");
assert(/不会生成或发送/.test(detailVideoContract), "plan-only detail must say generation and video submission stay off");
assert(/shots:\s*shots\.map\(summarizeShotIndexItem\)/.test(directorAgentActionSource), "Agent snapshot must keep a project shot index for text-target resolution");
assert(/shotIdsMentionedInIntent/.test(directorAgentActionSource), "Agent action builder must resolve explicit shot mentions from natural language");
assert(/sourceContextShotIds/.test(directorAgentActionSource), "Agent action source context must carry resolved shot targets");

assert(/minimal-agent-permission-menu/.test(minimalAgentPanelSource), "MinimalAgentPanel must render the three-mode status");
assert(/aria-label="AI 选择的做法"[\s\S]*AI 选择的做法/.test(minimalAgentPanelSource), "selected strategy should be shown as the AI chosen approach, not an internal skill term");
assert(/minimal-agent-skill-hint[\s\S]*想换做法[\s\S]*直接在下面输入框说/.test(minimalAgentPanelSource), "strategy changes should be requested through natural-language Agent input instead of manual skill buttons");
assert(!/minimal-agent-skill-actions|selectedSkillOverrides|directorSkillOverridePrompts/.test(minimalAgentPanelSource), "MinimalAgentPanel must not expose manual skill override controls in the Agent-first path");
assert(/先整理[\s\S]*可做参考[\s\S]*可发视频/.test(minimalAgentPanelSource), "MinimalAgentPanel must show the three creator-facing modes");
assert(/const currentVideoPermissionContract = videoPermissionContractForUi/.test(minimalAgentPanelSource), "visible permission boundary must drive current Agent actions");
assert(/function visibleVideoPermissionContractFor\(contract: AgentVideoPermissionContract\)[\s\S]*agentVideoPermissionForUi\(contract/.test(minimalAgentPanelSource), "visible permission boundary must be reusable for newly staged actions");
assert(/referenceGenerationBlockedByContract\s*=\s*!agentVideoPermissionAllowsReference\(currentVideoPermissionContract\)/.test(minimalAgentPanelSource), "reference actions must follow the visible permission boundary");
assert(/videoPermissionBlockedByContract\s*=\s*!videoCanResume\s*&&\s*!agentVideoPermissionAllowsVideo\(currentVideoPermissionContract\)/.test(minimalAgentPanelSource), "video actions must follow the visible permission boundary while keeping result queries available");
assert(/agentVideoPermissionLabel\(videoPermissionContractForUi\)/.test(minimalAgentPanelSource), "permission status labels must still match the visible permission boundary");
assert(/agentVideoPermissionDetail\(currentVideoPermissionContract\)/.test(minimalAgentPanelSource), "blocked action help text must match the visible permission boundary");
assert(/const videoCanResume = Boolean\(videoSendAction\?\.canResume\)/.test(minimalAgentPanelSource), "submitted Seedance jobs with a resume command must remain actionable in the Agent panel");
assert(/videoCanResume[\s\S]*\? "查询结果"/.test(minimalAgentPanelSource), "resumable Seedance jobs must show a query-result action instead of a dead submitted state");
assert(/if \(referenceGenerationBlockedByContract\)[\s\S]*agentVideoPermissionForMode\("reference_allowed"\)[\s\S]*再点生成参考继续[\s\S]*return;/.test(minimalAgentPanelSource), "reference generation must first upgrade the session boundary from the explicit action button");
assert(/if \(referenceGenerationBlockedByContract\)[\s\S]*agentVideoPermissionForMode\("reference_allowed"\)[\s\S]*再点生成结束画面继续[\s\S]*return;/.test(minimalAgentPanelSource), "special end-frame generation must first upgrade the session boundary from the explicit action button");
assert(/if \(!videoCanResume && videoPermissionBlockedByContract\)[\s\S]*agentVideoPermissionForMode\("video_allowed"\)[\s\S]*再点发送视频继续[\s\S]*return;/.test(minimalAgentPanelSource), "video submission must first upgrade the session boundary from the explicit action button");
assert(/const showRealSampleDetailButton = realSampleDetailNeedsReview \|\| !referenceGenerationBlockedByProject/.test(minimalAgentPanelSource), "reference generation detail button should hide while the project is not saved instead of showing a dead button");
assert(/showRealSampleDetailButton[\s\S]*disabled=\{realSampleDetailNeedsReview[\s\S]*realSampleAction\.disabled \|\| !realSampleAction\.keyConfigured \|\| realSampleBusy/.test(minimalAgentPanelSource), "reference generation detail button should not be disabled only because the current boundary is plan-only");
assert(/disabled=\{referenceGenerationBlockedByProject \|\| endFrameAction\.disabled/.test(minimalAgentPanelSource), "end-frame detail button should not be disabled only because the current boundary is plan-only");
assert(/disabled=\{videoCanResume[\s\S]*\?\s*videoPermissionBlockedByProject[\s\S]*:\s*videoPermissionBlockedByProject \|\| Boolean\(videoSendAction\.disabled\)/.test(minimalAgentPanelSource), "video detail button should not be disabled only because the current boundary is plan-only");
assert(/\(videoAlreadySent && !videoCanResume\)/.test(minimalAgentPanelSource), "resumable submitted video jobs must not be disabled as already-sent");
assert(/const realSampleDetailAction = realSampleDetailNeedsReview[\s\S]*openReferenceReviewFromDetails[\s\S]*pointToMainReferenceAction/.test(minimalAgentPanelSource), "reference detail button must route review-ready assets to review and otherwise point back to the bottom primary action");
assert(/function pointToMainVideoAction\(\)[\s\S]*点下方「发送」，继续查询视频结果[\s\S]*点下方「发送」，让 AI 导演发送视频/.test(minimalAgentPanelSource), "video detail button must explain the bottom primary action instead of submitting from details");
assert(/onClick=\{pointToMainVideoAction\}/.test(minimalAgentPanelSource), "video detail button must not execute submit/query directly");
assert(/onClick=\{runFooterEndFrameGeneration\}/.test(minimalAgentPanelSource), "end-frame detail button must reuse the single footer action path");
assert(/\.minimal-agent-permission-mode/.test(stylesSource), "three-mode status needs styling");

assert(/resumeProjectSeedanceVideo/.test(seedanceVideoSubmitActionSource), "Seedance video action hook must call the resume endpoint for queued jobs");
assert(/runtimeActionState[\s\S]*seedanceActionStateFromRuntime\(realChainState\)/.test(seedanceVideoSubmitActionSource), "Seedance video action hook must derive resumable state from the project runtime chain");
assert(/effectiveActionState\.status === "submitted" && effectiveActionState\.canResume/.test(seedanceVideoSubmitActionSource), "Seedance video action hook must branch from effective submitted state to resume query");
assert(/options\?\.videoPermissionContract[\s\S]*!agentVideoSubmitContractAllowsVideo\(options\.videoPermissionContract\)[\s\S]*本轮不发送视频/.test(seedanceVideoSubmitActionSource), "Seedance video action hook must hard-block new submits when the session contract disallows video");

assert(/useState<AgentVideoPermissionContract>\(defaultAgentVideoPermissionContract\)/.test(directorMode), "DirectorMode must own the session video submit contract");
assert(/permissionProjectKey[\s\S]*runtimeState\.project\.root[\s\S]*runtimeState\.sourceIndexSummary\.projectId/.test(directorMode), "DirectorMode must key the Agent execution boundary to the current project");
assert(/previousPermissionProjectKeyRef[\s\S]*setVideoPermissionContract\(defaultAgentVideoPermissionContract\)/.test(directorMode), "switching projects must reset the Agent execution boundary to plan-only");
assert(/detectAgentVideoPermissionContract\(\[draft\.script,\s*draft\.style\]/.test(directorMode), "NewVideoStart confirmation must write creator generation limits into the session contract");
assert(/sessionVideoSendAction[\s\S]*disabled:\s*true[\s\S]*ready:\s*false/.test(directorMode), "DirectorMode must turn the contract into a disabled video action");
assert(/sessionSendSeedanceVideo[\s\S]*videoPermissionContract/.test(directorMode), "DirectorMode must inject the session video permission contract into submit calls");
assert(/sessionRetryMissingBatch\s*=\s*videoPermissionAllowsReference/.test(directorMode), "reference generation actions must be gated by the session contract");
assert(/onRetryMissing=\{sessionRetryMissingBatch\}/.test(directorMode), "CreatorDeskPanels must receive the contract-aware reference action");
assert(/videoSendAction=\{sessionVideoSendAction\}/.test(directorMode), "CreatorDeskPanels must receive the contract-aware video action");
assert(/const visibleAgentCommand = useMemo[\s\S]*允许做参考[\s\S]*允许发视频/.test(directorMode), "DirectorMode must adapt the visible Agent command to the current execution boundary");
assert(/agentCommand=\{visibleAgentCommand\}/.test(directorMode), "MinimalAgentPanel must receive the boundary-aware CreatorDesk Agent command");
assert(/videoSendAction=\{videoSendAction\}/.test(directorMode), "MinimalAgentPanel must receive the raw video action and enforce the visible boundary itself");
assert(/onRetryMissingBatch=\{sessionRetryMissingBatch\}/.test(directorMode), "MinimalAgentPanel must route bottom reference generation through the current story fallback before legacy one-shot generation");
assert(/onSendVideo=\{sessionSendSeedanceVideo\}/.test(directorMode), "CreatorDeskPanels must use the contract-aware submit callback");
assert(/onSendSeedanceVideo=\{onSendSeedanceVideo\}/.test(directorMode), "MinimalAgentPanel must own the bottom permission upgrade before submitting video");
assert(/onRunExport=\{onRunExport\}/.test(directorMode), "MinimalAgentPanel must receive the project export action");
assert(/onOpenResultView=\{onOpenDirectorView\}/.test(directorMode), "MinimalAgentPanel must receive a result-view navigation callback");
assert(/onVideoPermissionContractChange=\{setVideoPermissionContract\}/.test(directorMode), "MinimalAgentPanel must write back to the DirectorMode session");
assert(/const footerDirectAction = canOfferFooterDirectAction/.test(minimalAgentPanelSource), "MinimalAgentPanel must map empty-composer state to the next concrete bottom action");
assert(/agentProjectRequirementCopy\(\{[\s\S]*localProjectBusy[\s\S]*canCreateLocalProject:\s*canResolveProjectFromFooter[\s\S]*\}\)/.test(minimalAgentPanelSource), "bottom primary action must share local-project requirement copy with CreatorDeskPanels");
assert(/if\s*\(footerDirectAction\)\s*\{[\s\S]*perform:\s*footerDirectAction\.perform/.test(minimalAgentPanelSource), "bottom primary operation must execute the current direct generation or video action before falling back to plan confirmation");
assert(/const realSampleLabel[\s\S]*referenceGenerationBlockedByContract[\s\S]*"允许做参考"/.test(minimalAgentPanelSource), "plan-only reference next action must ask to allow references before generation");
assert(/function runFooterReferenceGeneration\(\)[\s\S]*if \(referenceGenerationBlockedByContract\)[\s\S]*agentVideoPermissionForMode\("reference_allowed"\)[\s\S]*再点生成参考继续[\s\S]*return;[\s\S]*runtimeState\.visualMemory\.summary\.missing > 0 && onRetryMissingBatch[\s\S]*void onRetryMissingBatch\(\)[\s\S]*return;[\s\S]*void onCreateP6RealSample\(\{ scope: "project", videoPermissionContract: currentVideoPermissionContract \}\)/.test(minimalAgentPanelSource), "bottom reference action must upgrade the visible boundary, then prefer story-flow missing reference generation before the legacy project sample fallback");
assert(/const videoActionLabel[\s\S]*videoPermissionBlockedByContract[\s\S]*"允许发视频"/.test(minimalAgentPanelSource), "plan-only video next action must ask to allow video before submission");
assert(/function runFooterVideoAction\(\)[\s\S]*if \(!videoCanResume && videoPermissionBlockedByContract\)[\s\S]*agentVideoPermissionForMode\("video_allowed"\)[\s\S]*再点发送视频继续[\s\S]*return;[\s\S]*void onSendSeedanceVideo\(\{ videoPermissionContract: currentVideoPermissionContract \}\)/.test(minimalAgentPanelSource), "bottom video action must upgrade the visible boundary before a later video submission click");
assert(/const commandFooterDirectAction = agentCommandKind === "generate_references"[\s\S]*agentCommandKind === "submit_video"[\s\S]*agentCommandKind === "resume_video"/.test(minimalAgentPanelSource), "bottom primary action must prefer the unified CreatorDesk Agent command before legacy fallbacks");
assert(/onOpenResultView\?\.\(agentCommand\.targetView\)/.test(minimalAgentPanelSource), "open-view Agent commands must use the same bottom primary action path");

console.log("minimal-agent-p1-contract-test passed");
