import { createHash } from "node:crypto";
import { existsSync } from "node:fs";
import { mkdir, mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";

import { buildPreviewExportState } from "../src/core/previewExport.ts";
import { buildExportWorkerState, executeExportWorkerPlan } from "../src/core/exportWorker.ts";
import {
  confirmProjectVibeCreativeLoop,
  hashProjectVibeFacts,
  openProjectVibe,
  saveProjectVibe,
  stageProjectVibeCreativeLoop,
  type ProjectVibeDocument,
} from "../src/project/index.ts";
import { createLocalProjectVibeStorageAdapter } from "../src/project/localProjectVibeStorage.ts";

function assert(condition: unknown, message: string): asserts condition {
  if (!condition) throw new Error(`FAIL: ${message}`);
}

function hasFlag(name: string): boolean {
  return process.argv.includes(name);
}

function sha256(value: Buffer | string): string {
  return `sha256:${createHash("sha256").update(value).digest("hex")}`;
}

async function writeText(projectRoot: string, relativePath: string, content: string) {
  const target = path.join(projectRoot, relativePath);
  const scoped = path.relative(projectRoot, target);
  if (scoped.startsWith("..") || path.isAbsolute(scoped)) throw new Error(`outside project root: ${relativePath}`);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content, "utf8");
}

async function writeBytes(projectRoot: string, relativePath: string, content: Buffer) {
  const target = path.join(projectRoot, relativePath);
  const scoped = path.relative(projectRoot, target);
  if (scoped.startsWith("..") || path.isAbsolute(scoped)) throw new Error(`outside project root: ${relativePath}`);
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, content);
}

class DiskExportAdapter {
  constructor(private readonly projectRoot: string) {}

  async mkdir(relativePath: string) {
    await mkdir(path.join(this.projectRoot, relativePath), { recursive: true });
  }

  async writeFile(relativePath: string, content: string) {
    await writeText(this.projectRoot, relativePath, content);
  }
}

const tinyPng = Buffer.from(
  "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/p9sAAAAASUVORK5CYII=",
  "base64",
);

const generatedAt = "2026-05-19T00:00:00.000Z";
const keep = hasFlag("--keep");
const projectRoot = await mkdtemp(path.join(tmpdir(), "vibe-mvp-full-chain-local-"));

try {
  const sampleProject = JSON.parse(await readFile("sample-projects/mvp-demo/project.vibe", "utf8")) as ProjectVibeDocument;
  sampleProject.manifest.projectId = "mvp_full_chain_local_smoke";
  sampleProject.manifest.title = "MVP Full Chain Local Smoke";
  sampleProject.manifest.createdAt = generatedAt;
  sampleProject.manifest.updatedAt = generatedAt;
  sampleProject.manifest.runtimeFixtureAuthority = false;
  sampleProject.runs = [];
  sampleProject.sourceIndex.runReceiptRefs = [];

  for (const asset of sampleProject.assets) {
    assert(asset.path, `sample asset ${asset.id} should have a local path`);
    await writeText(projectRoot, asset.path, `mock local locked asset for ${asset.id}\nproviderCalled=false\n`);
  }
  await writeText(projectRoot, "README.md", [
    "# MVP Full Chain Local Smoke",
    "",
    "This project is generated by a local/mock harness.",
    "It is not evidence of real Image2, Jimeng, or cloud TTS provider execution.",
    "",
  ].join("\n"));

  const saveInitial = await saveProjectVibe(createLocalProjectVibeStorageAdapter(projectRoot), sampleProject, "project.vibe");
  assert(saveInitial.ok, `initial Project.vibe save failed: ${saveInitial.errors.join("; ")}`);
  const openInitial = await openProjectVibe(createLocalProjectVibeStorageAdapter(projectRoot), "project.vibe");
  assert(openInitial.ok && openInitial.project, `initial Project.vibe open failed: ${openInitial.errors.join("; ")}`);

  const staged = stageProjectVibeCreativeLoop({
    project: openInitial.project,
    userIntent: "把第二个镜头改成更明确的项目验收样片节奏，但只进入本地 mock 生成。",
    selectedShotId: "S02",
    generatedAt,
    projectRoot,
    projectPath: "project.vibe",
  });
  assert(staged.status === "awaiting_confirmation", `staged draft should wait for confirmation: ${staged.blockedReasons.join("; ")}`);
  assert(staged.projectVibeWritten === false, "staged draft must not write Project.vibe");
  assert(staged.providerCalled === false && staged.workerSpawned === false, "staged draft must not call providers or workers");

  const factHashBefore = hashProjectVibeFacts(openInitial.project);
  const confirmed = confirmProjectVibeCreativeLoop({
    project: openInitial.project,
    userIntent: "把第二个镜头改成更明确的项目验收样片节奏，但只进入本地 mock 生成。",
    selectedShotId: "S02",
    generatedAt,
    projectRoot,
    projectPath: "project.vibe",
    userConfirmed: true,
  });
  assert(confirmed.status === "project_facts_written", `confirmation should write project facts: ${confirmed.blockedReasons.join("; ")}`);
  assert(confirmed.nextProject, "confirmed flow should return the updated Project.vibe document");
  assert(confirmed.providerCalled === false && confirmed.workerSpawned === false, "project facts confirmation must not call providers or workers");
  assert(hashProjectVibeFacts(confirmed.nextProject) !== factHashBefore, "confirmed project facts should change the Project.vibe fact hash");

  const saveConfirmed = await saveProjectVibe(createLocalProjectVibeStorageAdapter(projectRoot), confirmed.nextProject, "project.vibe");
  assert(saveConfirmed.ok, `confirmed Project.vibe save failed: ${saveConfirmed.errors.join("; ")}`);

  const media = [
    { shotId: "S01", durationSeconds: 4 },
    { shotId: "S02", durationSeconds: 5 },
    { shotId: "S03", durationSeconds: 4 },
  ];
  for (const item of media) {
    await writeBytes(projectRoot, `outputs/keyframes/${item.shotId}_start.png`, tinyPng);
    await writeText(projectRoot, `outputs/videos/${item.shotId}.mp4`, `mock video placeholder for ${item.shotId}\nnot a rendered provider video\n`);
    await writeText(projectRoot, `receipts/mock/${item.shotId}.json`, `${JSON.stringify({
      receiptKind: "mvp_full_chain_local_mock_media",
      schemaVersion: "0.1.0",
      shotId: item.shotId,
      generatedAt,
      providerCalled: false,
      externalProviderCalled: false,
      localMockArtifact: true,
      imagePath: `outputs/keyframes/${item.shotId}_start.png`,
      videoPath: `outputs/videos/${item.shotId}.mp4`,
    }, null, 2)}\n`);
  }

  const shots = confirmed.nextProject.shots.map((shot) => ({
    id: shot.id,
    actId: "A1",
    sectionId: shot.sectionId,
    title: shot.title,
    storyFunction: shot.intent,
    startFrame: `outputs/keyframes/${shot.id}_start.png`,
    status: "keyframe_pair_ready",
    gates: { identity: "PASS", scene: "PASS", pair: "PASS", story: "PASS", prop: "N/A", style: "PASS" },
    issues: [],
  }));
  const taskViews = shots.map((shot) => ({
    shotId: shot.id,
    job: {
      id: `mock_start_frame_job_${shot.id}`,
      slot: "image.generate",
      requiredMode: "mock_start_frame",
      providerId: "local-mock-start-frame-placeholder",
      status: "success",
      promptPath: `prompts/${shot.id}.md`,
      outputPath: shot.startFrame,
      references: [shot.startFrame],
      issues: [],
    },
    taskRun: {
      taskId: `mock_start_frame_job_${shot.id}`,
      localStatus: "succeeded",
      providerStatus: "mock_success",
      providerId: "local-mock-start-frame-placeholder",
      retryCount: 0,
      stallTimeoutSeconds: 0,
      tempDirs: [],
      expectedOutputs: [shot.startFrame],
      actualOutputs: [shot.startFrame],
    },
    manifestMatch: {
      taskId: `mock_start_frame_job_${shot.id}`,
      expectedOutputPath: shot.startFrame,
      actualOutputPath: shot.startFrame,
      status: "matched",
      outputExists: true,
      blockers: [],
      warnings: ["local mock start frame placeholder; not real provider media"],
    },
  }));

  const previewExport = buildPreviewExportState({
    generatedAt,
    projectRoot,
    selectedShotId: "S02",
    previewEvents: [],
    shots,
    jobs: taskViews.map((view) => view.job),
    taskRuns: taskViews.map((view) => view.taskRun),
    taskViews,
    manifestMatches: taskViews.map((view) => view.manifestMatch),
    generationHealthReports: shots.map((shot) => ({
      reportId: `mock_health_${shot.id}`,
      taskPlanId: `mock_start_frame_plan_${shot.id}`,
      jobId: `mock_start_frame_job_${shot.id}`,
      shotId: shot.id,
      expectedOutputPath: shot.startFrame,
      outputExists: true,
      manifestStatus: "matched",
      qaStatus: "pass",
      stalePrompt: false,
      assetReadinessStatus: "ready",
      healthStatus: "formal_ready",
      blockers: [],
      warnings: ["mock/local only"],
      nextAction: "ready_for_local_export_contract",
    })),
    qaPromotionReports: shots.map((shot) => ({
      reportId: `mock_promotion_${shot.id}`,
      taskPlanId: `mock_start_frame_plan_${shot.id}`,
      jobId: `mock_start_frame_job_${shot.id}`,
      shotId: shot.id,
      candidatePath: shot.startFrame,
      formalPath: shot.startFrame,
      promotionStatus: "promoted",
      requiredGates: {
        expectedOutput: true,
        manifestMatch: true,
        promptFresh: true,
        assetReadiness: true,
        qaPass: true,
      },
      blockers: [],
      warnings: ["mock/local only"],
      canPromoteToFormal: true,
    })),
    issues: [],
    defaultImageHoldSeconds: 3,
  });
  assert(previewExport.draftPreview.status === "draft_only", "draft preview should be draft_only with local placeholders");
  assert(previewExport.formalPreview.status === "blocked", "local demo smoke should not pretend image holds are formal rendered video");
  assert(previewExport.exportPackagePlan.providerSubmissionForbidden === true, "preview export must forbid provider submission");

  const exportState = buildExportWorkerState({
    source: previewExport,
    projectVibe: confirmed.nextProject,
    projectTitle: confirmed.nextProject.manifest.title,
    exportRoot: "exports/mvp-full-chain-local-smoke",
    profileSelection: ["rough_cut", "asset_package", "storyboard_table", "developer_archive"],
    generatedAt,
    executionMode: "adapter_execution",
    confirmation: true,
  });
  assert(exportState.canExecute, `export package contract should be executable: ${exportState.blockers.join("; ")}`);
  assert(exportState.hardLocks.noProviderSubmit === true, "export worker must forbid provider submit");
  const exportResult = await executeExportWorkerPlan(exportState, new DiskExportAdapter(projectRoot));
  assert(exportResult.ok, `export worker execution failed: ${exportResult.errors.join("; ")}`);

  const manifestPath = path.join(projectRoot, "exports/mvp-full-chain-local-smoke/export_manifest.json");
  const manifest = JSON.parse(await readFile(manifestPath, "utf8"));
  assert(manifest.readiness === "ready", "export manifest should be ready");
  assert(manifest.mvpPackage.projectVibeIncluded === true, "export manifest should include Project.vibe");
  assert(manifest.mvpPackage.previewMediaCount === 3, "export manifest should include three preview media entries");
  assert(manifest.mvpPackage.videoResultCount === 3, "export manifest should track three video slots");
  assert(manifest.mvpPackage.videoMissingCount === 3, "local smoke must keep video slots missing rather than approving mock placeholders");
  assert(manifest.mvpPackage.videoApprovedCount === 0, "local smoke must not approve mock video placeholders");
  assert(manifest.mvpPackage.receiptCount >= 1, "export manifest should include project receipt evidence");

  const report = {
    ok: true,
    smokeKind: "demo_mvp_local_mock",
    realProviderProjectAcceptance: false,
    providerCalled: false,
    externalProviderCalled: false,
    liveSubmitAllowed: false,
    projectRoot,
    stagedStatus: staged.status,
    confirmedStatus: confirmed.status,
    queuedTaskRunCount: confirmed.queuedTaskRunIds.length,
    artifactSummary: {
      lockedAssets: confirmed.nextProject.assets.length,
      startFrames: media.length,
      videoPlaceholders: media.length,
      mockReceiptSha256: sha256(await readFile(path.join(projectRoot, "receipts/mock/S01.json"))),
    },
    export: {
      root: "exports/mvp-full-chain-local-smoke",
      manifestPath: path.relative(projectRoot, manifestPath).replace(/\\/g, "/"),
      executedWrites: exportResult.executed.length,
      readiness: manifest.readiness,
      profiles: manifest.profileSelection,
    },
    notes: [
      "This smoke uses local/mock artifacts only.",
      "It proves Project.vibe staged confirmation, local project facts, preview/export contracts, and package writes.",
      "It does not prove Image2, Jimeng/Seedance, cloud TTS, real render quality, or provider queue behavior.",
    ],
  };
  await writeText(projectRoot, "reports/mvp-full-chain-local-smoke.json", `${JSON.stringify(report, null, 2)}\n`);

  console.log(`mvp-full-chain-local-smoke: ok projectRoot=${projectRoot} export=${report.export.manifestPath}`);
} finally {
  if (!keep) {
    await rm(projectRoot, { recursive: true, force: true });
  } else {
    assert(existsSync(projectRoot), "kept project root should still exist");
  }
}
